### ISSUE TITLE
Set property minDate in controller

### ISSUE THREAD

**Issue by lait1989** [fragaria/angular-daterangepicker#100]
Hi! Help me please with set property minDate in controller. I try <h2>$scope.date = {options: {minDate: '2014-01-01'}}</h2> or <h2>$scope.date = {minDate: '2014-01-01'}</h2>, but i have no effect. Thanks.

**Comment by krtek** [comment]
The date must be [moment.js](http://momentjs.com/) object and you have to pass it to options attribute: Try:

```
 $scope.options = {minDate: moment('2014-01-01')}
```
