### ISSUE TITLE
How to Highlight Particular Dates

### ISSUE THREAD

**Issue by pranaysonisoft** [fragaria/angular-daterangepicker#104]
add option for events

var events = [ 
    { Title: "Five K for charity", Date: new Date("02/12/2016") ,cssClass:'red'}, 
    { Title: "Dinner", Date: new Date("03/12/2016") ,cssClass:'green'}, 
    { Title: "Meeting with manager", Date: new Date("04/12/2016"),cssClass:'Blue' }
];

**Comment by eassa** [comment]
try to use moment.js 

example in angular : 

$scope.opts = {
ranges: {
'Last 7 Days': [moment().subtract(6, 'days'), moment()],
'Last 15 Days': [moment().subtract(15, 'days'), moment()],
'Last 30 Days': [moment().subtract(29, 'days'), moment()]
}

**Comment by krtek** [comment]
Thanks @eassa, that should work. 

Closing.
