### ISSUE TITLE
Trigger external open

### ISSUE THREAD

**Issue by antonellopasella** [fragaria/angular-daterangepicker#106]
Can I open the calendar other than clicking the input element?

**Comment by raygerrard** [comment]
You can either trigger a click event on the element:

    element.trigger("click");

Or you call the show method on the daterangepicker instance:

    element.data("daterangepicker").show();

**Comment by mparisi76** [comment]
This does not work for me. Is it possible to open the daterangepicker using a button outside of daterangepicker?

**Comment by martin-brennan-csnet** [comment]
This worked for me, on the click event of the button I wanted to use to open the datepicker I just did:

```
$('#date-picker-input-id').data('daterangepicker').show();
```

**Comment by Drumstix42** [comment]
This is how I solved the issue of opening from an external button:

Controller/Component side:
```
vm.dateRangePicker = {
    date: {
        // date options here
    }
    picker: null, // daterangepicker initialized on this prop
    toggle() {
        // need to use $timeout here to avoid $apply errors for digest cycle
        $timeout(() => {
            this.picker.toggle();
         });
    }
    options: {
        // options here
    }
}
```

From template side:
(Your picker input should point at `vm.dateRangePicker.picker` for this example)
```
<button type="button" ng-click="vm.dateRangePicker.toggle()">
```

Bonus template side to track "state" of button:
```
ng-class="{ 'active': vm.dateRangePicker.picker.isShowing }"
```
