### ISSUE TITLE
eventHandlers that defined multiple event handlers cannot work properly

### ISSUE THREAD

**Issue by wubin1989** [fragaria/angular-daterangepicker#107]
e.g. 

```
vm.opts = {
        applyClass: '...',
        locale: {
            ...
        },
       eventHandlers: {
          'show.daterangepicker': function(ev,picker){console.log(123);},
          'hide.daterangepicker': function(ev,picker){console.log(456);},
       }
    };
```

it is always printing out 456. The handler binded on 'show.daterangepicker' doesn't work!
Does anyone have the resolve solution?

**Comment by wubin1989** [comment]
I solved the problem by myself

**Comment by wubin1989** [comment]
I want to commit here, but 'Permission to fragaria/angular-daterangepicker.git denied'.

Here is my solution below: 

change this 
          for (eventType in _ref) {
            callbackFunction = _ref[eventType];
            _results.push(el.on(eventType, function() {
              return $scope.$evalAsync(callbackFunction);
            }));
          }
to
          for (eventType in _ref) {
            el.on(eventType, function(e) {
              var eventName = e.type + '.' + e.namespace;
              return $scope.$evalAsync(_ref[eventName]);
            });
          }

Hope to help others.

**Comment by tomerb15** [comment]
I just encountered the same. Any idea how to fix?

**Comment by raygerrard** [comment]
see pull request https://github.com/fragaria/angular-daterangepicker/pull/111
