### ISSUE TITLE
No format applied with initial display of date range

### ISSUE THREAD

**Issue by bayy** [fragaria/angular-daterangepicker#11]
In html

```
   <input type="daterange" date-range-picker id="daterange3" class="form-control date-picker" type="text"
          name="date" ng-model="class.dateRange" options="opts" required/>
```

In controller:

```
    $scope.class.dateRange = {startDate: moment().subtract("days", 1), endDate: moment()};

    $scope.opts = {
        format: 'MM/DD/YYYY h:mm A',
        timePicker: true,
        timePickerIncrement: 5
    };
```

When the page is first loaded, the format is not applied. It shows "2014-09-30 - 2014-10-01". Once I selected a new date/time, the format is applied and shows "10/01/2014 8:00 AM - 10/01/2014 11:59 PM".

The format should be applied at the initial display.

**Comment by sarates** [comment]
It still reproducing. When it will be fixed?
