### ISSUE TITLE
ng-change is not triggered

### ISSUE THREAD

**Issue by mlenser** [fragaria/angular-daterangepicker#110]
When selecting a new date ng-change isn't triggered.

**Comment by mlenser** [comment]
Nevermind

**Comment by vmkumar** [comment]
How to fix ng change triggering, thanks in advance

**Comment by beiduo** [comment]
one way i can think of is to call the 'change' function inside the 'apply.daterangepicker' event handler, not sure if there is a better or more formal solution.

**Comment by beiduo** [comment]
@vmkumar one way i can think of is to call the 'change' function inside the 'apply.daterangepicker' event handler, not sure if there is a better or more formal solution.
