### ISSUE TITLE
Single datepicker model value endDate = null

### ISSUE THREAD

**Issue by raygerrard** [fragaria/angular-daterangepicker#114]
When a datepicker is configured to use a single date picker, the model value is stored as an object containing a startDate and endDate of null, I would propose that in this case it is stored as a single date object.

**Comment by josemadev** [comment]
its will be fantactic for set ngmodel :)

**Comment by raygerrard** [comment]
Thanks @josemadev, getter/setter would be a good workaround if I had a single prop on the model. In my case I am including a datepicker in an ng-repeat.

**Comment by raygerrard** [comment]
https://github.com/fragaria/angular-daterangepicker/pull/116

**Comment by raygerrard** [comment]
merged in 7cdc3f47b9e68e60c09238be7739bc8a43ded68d

**Comment by wesley3523** [comment]
Since this update my input field is not updating the date when selecting a date in the picker and always goes back to current date time. But when i echo out my ng-model value i see the selected date. Any idea?

i appreciate it
