### ISSUE TITLE
callback function when NOT using an input text

### ISSUE THREAD

**Issue by tomerb15** [fragaria/angular-daterangepicker#115]
Hey, Thanks for angularize this awesome picker!
I have a couple of questions:
1. What is the equivalent for passing a callback function, something like: (I want to be able to call `cb`)

```
$('#reportrange').daterangepicker({
        ranges: {
           'Today': [moment(), moment()],
           'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
           'Last 7 Days': [moment().subtract(6, 'days'), moment()],
           'Last 30 Days': [moment().subtract(29, 'days'), moment()],
           'This Month': [moment().startOf('month'), moment().endOf('month')],
           'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }
    }, cb);
```
1. When i use `ranges` the calander is opened by default, while in the following example, it opens only if "Custom Range" is selected. I know its out of your scope but it would be great if you know the answer.
   http://demo.improvely.com/reports/membershipsite/ads?tab=source&filters[ad]=1&filters[source]=Google%20AdWords&imt=1&utm_campaign=Date+Range+Picker&utm_source=Site+Ads&utm_medium=Banner&utm_content=Blog+Demo+Image

Thanks again!

**Comment by raygerrard** [comment]
You can configure callbacks within options, see example below:

    <input date-range-picker class="form-control date-picker" type="text" ng-model="date" options="{eventHandlers: {'show.daterangepicker': function(ev, picker) { ... }}}"/>

You can find list of events here: http://www.daterangepicker.com/#options

**Comment by tomerb15** [comment]
Unfortunately it works with just one eventHandler. if i try to configure 2 or more, only the last defined is invoked for all events.

**Comment by raygerrard** [comment]
There is already a pull request for this issue https://github.com/fragaria/angular-daterangepicker/pull/111
