### ISSUE TITLE
Manual date entry sets the year to 0

### ISSUE THREAD

**Issue by dainbrump** [fragaria/angular-daterangepicker#117]
When I try to manually enter the start and end dates, the year gets set to 0 and the field loses focus. This doesn't seem to happen in the original plugin.

``` javascript
datePicker: {
  min: moment().tz(BRAND.timezone).startOf('day').format(),
  options: {
    separator: ' to ',
    timePicker: true,
    timePickerIncrement: 5,
    format: 'MM/DD/YYYY h:mm A',
    timeZone: moment().tz(BRAND.timezone).utcOffset(),
    eventHandlers: {
      'hide.daterangepicker': function (event, picker) {
        eventcontroller.event.startDate = picker.startDate.tz(BRAND.timezone).format();
        eventcontroller.event.endDate = picker.endDate.tz(BRAND.timezone).format();
      }
    }
  },
  startDate: null,
  endDate: null,
}
```

![daterange-picker](https://cloud.githubusercontent.com/assets/753798/10856387/d455bfce-7f1d-11e5-8fb8-956fac1b9711.png)

**Comment by fahadcv** [comment]
Is there any luck on it? even we see strange conversion happening on manual entry, especially when we automate testing with robotframework-selenium2library

as below conversion happen automatically.
1970 Oct 12 to 2020 Oct 12 ---> 1970 Oct 12 to 002

attached screen shot for reference,


![datepicker-screen](https://cloud.githubusercontent.com/assets/2744968/12776407/c146f11a-ca7b-11e5-9bde-5d5f0c7e573c.JPG)
0 Oct 12
