### ISSUE TITLE
how to set linkedCalendars =false?

### ISSUE THREAD

**Issue by edwardlau** [fragaria/angular-daterangepicker#124]
Hi , I see the exmapl.html bug not found set linkedCalendars? can u tell me how to set linkedCalendars? thx

**Comment by fahadcv** [comment]
hope below one may helpful for some one.... 

 scope.datePicker = {
                        options: {
                            linkedCalendars: false
                        },
                        range: {
                            startDate: null,
                            endDate: null
                        }
                    };
