### ISSUE TITLE
New Feature: when timepicker is enabled, if start/end days are the same, it should be shown only once

### ISSUE THREAD

**Issue by bayy** [fragaria/angular-daterangepicker#13]
When timepicker is enabled, if startDate and endDate have the same day, the day should only be shown once.
Here is an example with the following code:

``` javascript
    <input type="text" date-range-picker="{format: 'MM/DD/YYYY h:mm A', timePicker: true, timePickerIncrement: 30}" id="daterange3"
           class="form-control date-picker" type="text"
           name="daterangepicker" ng-model="class.dateRange"
           required/>
```

Instead of showing `10/09/2014 2:30 PM - 10/09/2014 5:30 PM`, it would be nice to show `10/09/2014 2:30 PM - 5:30 PM`

**Comment by jimmyt1988** [comment]
That'd be cool man!
