### ISSUE TITLE
Issue with watch or ng-change while inside a template.

### ISSUE THREAD

**Issue by dearn44** [fragaria/angular-daterangepicker#147]
I am using daterangepicker inside a template in order to create a date filter. The thing is even thought the input values change My warcher does not fire up. It is as if my model exists on some other separate scope. 

I tried ng-daterangepicker-plus and it does not seem to have this issue.

**Comment by maxm450** [comment]
Have the same issue. :+1:

**Comment by Wlada** [comment]
+1

**Comment by elvis-macak** [comment]
Add a pr https://github.com/fragaria/angular-daterangepicker/pull/194, to fix this bug.
