### ISSUE TITLE
Format is not applied correctly at initialization

### ISSUE THREAD

**Issue by elm-** [fragaria/angular-daterangepicker#15]
When trying to override the format there are two issues I observed:
1. it is not used for initial rendering of the first value
2. it is parsed in a wrong manner after applying it, e.g. in the format "DD.MM.YYYY" the  YYYY is parsed wrong.

To reproduce just take a look at the example.html in the default distribution and the field where it should render in a different format.

I didn't fully dive into the directive, but it seems that the format is not consistently applied at all conversion points interacting with ngModel, could that be the reason?

**Comment by KurtPreston** [comment]
This issue seems to be occurring again using the most recent code on angular 1.3.8.

**Comment by ReservedDeveloper** [comment]
Using v0.2.2, bootstrap-daterangepicker v2.1.17, and angular 1.5.0-rc.0, and also encountering this issue. Picker loads just fine, and operates as expected when clicking on any of the inputs. But the initial values in the input do not display with the expected format.

**Comment by sarates** [comment]
It still reproducing. When it will be fixed?
