### ISSUE TITLE
singleDatePicker throws TypeError: Cannot read property 'startDate' of undefined

### ISSUE THREAD

**Issue by xoloinc** [fragaria/angular-daterangepicker#150]
When you initiate the picker with an null value for date, the formatter push iteration fails, throwing a  
TypeError: Cannot read property 'startDate' of undefined 

The if statement first checks if singleDatePicker && date is set, if not, next step checks for objValue.startDate only, which makes the error to occur caused by objValue being a null value.

This should be fixed by adding a check for both objValue && objValue.startDate in the clause.

```
  if opts.singleDatePicker and objValue
        f(objValue)
      else if objValue.startDate
        [f(objValue.startDate), f(objValue.endDate)].join(opts.locale.separator)
      else ''
```

to 

```
   if opts.singleDatePicker and objValue
        f(objValue)
      else if objValue and objValue.startDate
        [f(objValue.startDate), f(objValue.endDate)].join(opts.locale.separator)
      else ''
```

or am I missing something?

**Comment by xoloinc** [comment]
just saw Add back check for undefined model value #136 solves this

**Comment by oles-bolotniuk** [comment]
As #136 is not merged yet in 2o18

In our project I fixed this by exposing model **date** and **options** objects to the controller scope:

**View:**
```
<div
  date-range-picker
  ng-model="date"
  options="options"
></div>
```

**Controller**:
```
$scope.options = {
  showDropdowns: true,
  opens: 'left',
  drops: 'down',
  applyClass: 'btn-primary'
};

$scope.date = {
  startDate: moment(),
  endDate: moment()
};
```
