### ISSUE TITLE
package.json missing 'main'

### ISSUE THREAD

**Issue by kentingxu** [fragaria/angular-daterangepicker#151]
There is no 'main' setting in package.json. This setting is needed by webpack to pack the app.
Please add this line to package.json.
`"main": "js/angular-daterangepicker.js",`

**Comment by noherczeg** [comment]
It is already there i nversion 0.2.2

**Comment by kentingxu** [comment]
Just checked. 'main' is still missing in package.json in version 0.2.2

**Comment by noherczeg** [comment]
Oh, sorry, I somehow thought that you were asking about bower.json.
