### ISSUE TITLE
How to disable initial date (today) ?

### ISSUE THREAD

**Issue by ShlomoRosenheimer** [fragaria/angular-daterangepicker#154]
My datepicker should be initalized with no inital dates. Using singleDatePicker: true

```
$scope.datePicker = {
      date: {}
    };
```

Everything works fine, setting the date etc. However, initially, the date picker displays the current date (today). How to disable it, so the input field is blank until I select a date? 

Using autoUpdateInput: false does not work

If I set my model to null, (datePicker.date = null) it says:

TypeError: Cannot read property 'startDate' of null

**Comment by fahadcv** [comment]
did you try to set ""

**Comment by wibbo** [comment]
Any update on this?

**Comment by vincez** [comment]
+1. I have the exact same issue

**Comment by parker789** [comment]
Fixed with my commit on issue #183
