### ISSUE TITLE
WARNING: Tried to load angular more than once.

### ISSUE THREAD

**Issue by anshul-budhiraja** [fragaria/angular-daterangepicker#166]
Hi
After I installed thi plugin in my meteor app, I am getting error
`WARNING: Tried to load angular more than once.`

In my version file I earlier had these two,

```
angular@1.0.3
angular:angular@1.4.7
```

After adding this package it added following dependencies 

```
angularjs:angular@1.3.15
dangrossman:bootstrap-daterangepicker@1.3.21_1
fragaria:angular-daterangepicker@0.1.12
momentjs:moment@2.10.6
```

Can someone please suggest asap.

**Comment by fabiomcj** [comment]
I Anshul, this problem can occur for several reasons. In [this](http://stackoverflow.com/questions/22595878/tried-to-load-angular-more-than-once) post there are some solutions, in the state I suggest you check the import of js files in your html page

**Comment by anshul-budhiraja** [comment]
Hi @fabiomcj , I am not able to find the root cause of this issue. I just tried with a sample app that has nothing except angular, meteor and this package. Even in this sample app I am getting the same issue.  I am uploading the zip file here of sample app I just tried. It will be appreciated if you can have a look. To run this app you just need to type meteor in cmd on folder location.
[dual-angular.zip](https://github.com/fragaria/angular-daterangepicker/files/175243/dual-angular.zip)
