### ISSUE TITLE
Options repeat themselves for every instance of the date range picker

### ISSUE THREAD

**Issue by Derekjohnson277** [fragaria/angular-daterangepicker#174]
I have three date range pickers in my application and the ranges seem to be copied everytime there in a new instance of the date picker. For example my first picker has one copy of the ranges, the second has two copies, and the third has three copies. Do you know why it would be doing this? I have tried giving all the date pickers separate names/IDs and separate option lists but that hasn't worked.
![capture](https://cloud.githubusercontent.com/assets/13419128/13785477/b5278944-eaa1-11e5-990e-1d9e355daf63.PNG)

**Comment by GeorgiyZhuravlev** [comment]
I have the same issue
