### ISSUE TITLE
How to set locale?

### ISSUE THREAD

**Issue by morfair** [fragaria/angular-daterangepicker#178]
How I to can set locale for month names?

**Comment by Smarello** [comment]
You can do something like this:

$scope.options = {
          locale: {
               monthNames: ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre'
               ]
         }
    };
