### ISSUE TITLE
Custom Range date range selection view

### ISSUE THREAD

**Issue by sauravGit** [fragaria/angular-daterangepicker#179]
Hi,
Whenever I click on custom Range, start date calendar view comes after end date  calendar view.
Ideally it should be Feb 2016 then March 2016. As I have attached the image it shows the opposite. Am I doing anything wrong?

![calendar](https://cloud.githubusercontent.com/assets/2225678/14113700/185846f6-f5a2-11e5-886c-cb90de4e3e0f.PNG)

**Comment by piquev** [comment]
hi had a similar problem, do you have css applying to the datepicker?
since the div of the datepicker is a child of body, it can cause some problems ...
