### ISSUE TITLE
startDate auto-defaults to today's date using singleDatePicker

### ISSUE THREAD

**Issue by parker789** [fragaria/angular-daterangepicker#183]
I'm trying to create a single date picker using the `singleDatePicker = true` option and passing `{ startDate: null, endDate: null }` into the model. 

After a quick run-through the code it seems one problem occurs during the `modelCtrl.$formatters.push()` - specifically:

```
var f;
f = function(date) {
  if (!moment.isMoment(date)) {
    return moment(date).format(opts.locale.format);
  } else {
    return date.format(opts.locale.format);
  }
};
if (opts.singleDatePicker && objValue) {
  return f(objValue);
}
```
- `(opts.singleDatePicker && objValue)` evaluates to `true` with `objValue = { startDate: null, endDate: null }`.  In turn the moment constructor is called with objValue as its param: `moment(objValue)`  ..which, being ugly, is still a perfectly O.K. moment constructor, but will result in today's date.  

I'm not sure if there are other pieces to the code which would need to be changed, but I unfortunately don't have time to make this fix myself at the moment.

**Comment by timvandijck** [comment]
This indeed is a problem, would be nice to see the pull request approved!

**Comment by parker789** [comment]
Looks like this project hasn't seen much activity from the lead dev; we'll see what happens. I've gone and switched from this date picker in my project because of this among other issues.. but would still be nice to have this fixed for those still using!
