### ISSUE TITLE
Model and Calendar don't sync when changing date outside of calendar view

### ISSUE THREAD

**Issue by stephengardner** [fragaria/angular-daterangepicker#186]
You can see this on the demo page with the clearable picker.

Clear the picker, then go back and look at the calendar.

It still shows whichever date you had originally picked.

Now click "Apply".

Nothing happens.

This is FAR from desired UX.

**Comment by danallen88** [comment]
+1 - running into this issue now and is presenting a real problem for us

**Comment by asso1985** [comment]
+1 - Same thing

**Comment by natan88** [comment]
+1

**Comment by d-tarasenka** [comment]
The same issue for me :(
