### ISSUE TITLE
Attempting to reset date range picker dates

### ISSUE THREAD

**Issue by dainbrump** [fragaria/angular-daterangepicker#19]
I have a form with the date picker on it. The initial {startDate:null, endDate:null} seems to work. If the user attempts to reset the form, I reset with null values but the picker shows the previously selected values and the resulting object data is set to null even after clicking apply.

**Comment by morgs32** [comment]
+1243

**Comment by blckshrk** [comment]
Same problem here!

**Comment by marcelinhov2** [comment]
Same problem here!

**Comment by frlinw** [comment]
Same here ! Still no solutions ?

My use case : 
User can filter a column with an input date-range-picker.
A request is sent to the server on data-ng-change
User can reset this filter
$scope.resetFilters = () ->
      $scope.mydate = 
        startDate: null
        endDate: null

Issue : If the user filter on "Today", reset filters and want to filter on "Today" again, he can't... because FROM and TO inputs are not reset so data-ng-change doesn't trigger

**Comment by marcelinhov2** [comment]
datepicker: (from, to) =>
    @$scope.datepicker = {}
    @$scope.datepicker.ranges = []
    @$scope.datepicker.range =
      startDate: if from and from.isValid() then from else null
      endDate: if to and to.isValid() then to else null

That's how I did the reset... You will need to put startDate/endDate inside
an object.

2015-04-14 14:46 GMT-03:00 frlinw <notifications@github.com>:

**Comment by frlinw** [comment]
Thanks for your answer!
It's not just about the reset, it's about the change trigger...
```
<input date-range-picker type="text" data-ng-model="myDateParam" data-ng-change="updateFilter()" options="dateRangePickerOptions">
```
With these options
```
$scope.dateRangePickerOptions = 
     ranges:
          'Today': [
                moment()
                moment()
           ]
```
If I select Today, nothing append because default startDate and endDate are ```moment()```.... So there is no change

If I try this : 
```
$scope.dateRangePickerOptions = 
     startDate: null
     endDate: null
     ranges:
          'Today': [
                moment()
                moment()
           ]
```
The datepicker is completely broken...

I have no choice but define a startDate and endDate different of my ranges. I did this : 
```
$scope.dateRangePickerOptions = 
     startDate: moment().startOf('month')
     endDate: moment().startOf('month')
     ranges:
          'Today': [
                moment()
                moment()
           ]
```
Problem is that datepickers are visible because it is considered as a custom date.

If you have a solution to hide datepickers if default startDate and endDate are "custom" or to have empty default startDate and endDate, I would owe you one...

**Comment by marcelinhov2** [comment]
Ok, I'd create a new directive to help you.

class DateRangePickerManager extends Controller
  constructor: (
    @$scope
    @$element
    @$timeout
  ) -> do @init

  init: =>
    do @wait_for_datepicker

  wait_for_datepicker: ->
    @$timeout(=>
      do @set_listeners
    , 500);

  set_listeners: ->
    @$element.on 'apply.daterangepicker', (ev, picker) =>
      @$scope.$apply =>
        @$scope.datepicker.range.startDate =
moment(picker.startDate).format('YYYY-MM-DD')
        @$scope.datepicker.range.endDate =
moment(picker.endDate).format('YYYY-MM-DD')

Import this directive to your project and add this directive at the
input date-range-picker.
It will solve your problem, I had the same thing and I't takes me some
hours.

2015-04-14 23:12 GMT-03:00 frlinw <notifications@github.com>:

**Comment by marcelinhov2** [comment]
So? Did you implemented this? It worked?

[]'s

2015-04-14 23:51 GMT-03:00 Marcelo Andrade <marceloandrade150@gmail.com>:

**Comment by bborowin** [comment]
I'm having what appears to be a related problem - here's a bit of code to illustrate the issue:

          <input
            date-range-picker
            readonly="readonly"
            class="col-md-3 form-control date-picker"
            type="text"
            ng-model="date"
            options="dateRangePickerOptions" />
          <button
            class="btn btn-primary"
            ng-click="date = null">
            {{ 'common.button.clear' | translate }}
          </button>

The clear button works (clears the `date` model and thus the text box), but when I open the dropdown, the old range is still highlighted. After selecting the same range again, clicking the Clear button does not have any effect (presumably because `date === null` already), and the range dates remain in the text box.

**Comment by marcelinhov2** [comment]
You need to put your vars inside an object and the clear need to set the
values as null.

It will work.
Em 22/04/2015 13:26, "bborowin" <notifications@github.com> escreveu:

**Comment by bborowin** [comment]
@marcelinhov2 looking at this again, I think my issue may be related to https://github.com/fragaria/angular-daterangepicker/issues/42 instead.
I am passing the ranges in an object, and it works as expected. Setting the model to `null` works only once (as far as clearing the textbox goes).

**Comment by marcelinhov2** [comment]
I had the same issue as you, but I did so many things that I don't
remember. But I will try to help you anyway.

First thing, I have created a method called *datepicker*. I use it just to
set the default values of the daterangepicker.

*datepicker*: (from, to) =>
    @$scope.datepicker = {}
    @$scope.datepicker.ranges = []
    @$scope.datepicker.range =
      startDate: if from and from.isValid() then from else null
      endDate: if to and to.isValid() then to else null

When I need to clean the date ( for example, a button to empty everything )
I just call this method and the magic happens.

Besides, I have a watcher too.

@$scope.$watch "datepicker.range", ((now, was, scope) =>
      if now.startDate and now.endDate
*        scope.form.valid_from = moment(now.startDate).format('YYYY-MM-DD')*
*        scope.form.valid_to = moment(now.endDate).format('YYYY-MM-DD')*
      else
*        scope.form.valid_from = null*
*        scope.form.valid_to = null*
), true

I just replicate the values from @$scope.datepicker to the @$scope.form
using the date format that I need to send to my webservice.

*Summarizing, you will need to have 2 different objects, one for the
daterangepicker and the other for your controller. If you use the same
object, you will have the problem that you describe.*

P.S.: I'm sorry for the explanation but I have a lot of difficult to teach.
It makes more sense in my head. I glad it will help you.

2015-04-22 14:51 GMT-03:00 bborowin <notifications@github.com>:

**Comment by frlinw** [comment]
Sorry marcelinhov2, didn't see your message!

No I didn't try what you suggest me. 
My final solution is to reset startDate and endDate from dateRangePickerOptions at default value. And this default value is the first sunday of the month (a date never picked by the user, so it's not a problem if he can't pick it...)

**Comment by marcelinhov2** [comment]
Try to use the watcher. It will solve your problem and you can have the
input empty. :)

2015-04-22 15:22 GMT-03:00 frlinw <notifications@github.com>:

**Comment by krtek** [comment]
Should be fixed in 0.1.17 – see `clearable` option.

**Comment by piyushsf** [comment]
I am having the same problem. I am using version 1.3. Can you suggest any workaround?

**Comment by roysupriya** [comment]
In my case, I am using daterangepicker with angular. My purpose is to watch any change in the model that stores the date range value and save it for an AJAX call later. I face the same issue as it hits the event twice whenever the date is change even if it is only 'Today': Once it is object with startDate and endDate properties, and the other time it is a string.

It can be made use of as an advantage.

```
    $scope.$watch(
    'rangeOfDate',
    function (newValue) {
        // Due to a known bug of open source library daterangepicker, the event is hit twice 
        //upon change. Once it is an object, and once it is a string. So, use appropriately.
        var selectedDateRange = new Object();
        if (typeof (newValue) == 'object') {
            selectedDateRange.startDate = new Date(newValue.startDate).toLocaleDateString();
            selectedDateRange.endDate = new Date(newValue.endDate).toLocaleDateString();
            //Do as you wish with this custom object
        }
        else if (typeof (newValue) == 'string') {
            alert("string");
        }               
    },
    false);
```

**Comment by FabianoLothor** [comment]
+1
