### ISSUE TITLE
Having two inputs instead of one

### ISSUE THREAD

**Issue by jdoan3** [fragaria/angular-daterangepicker#191]
Is it possible to split start and end date into 2 input fields?
But still keep the range option?

So that the output is like this:

Field 1: 2015/12/01 | Field 2: 2015/12/05

Instead of: 2015/12/01-2015/12/05
Similar to this : https://github.com/longbill/jquery-date-range-picker

**Comment by pherng** [comment]
Did anyone have the answer for this issue?
