### ISSUE TITLE
Selected label is not available for display

### ISSUE THREAD

**Issue by mominaetizaz** [fragaria/angular-daterangepicker#196]
Update angular-daterangepicker.js line number 135-142

On line 135 of the js file you need to add the field "label" so that we can use the text in the selected predefined ranges. That would mean the function should be function(start, end, label) and in the return object send { startDate: start, endDate: end, chosenLabel: label}. This change is inline with the data available from the bootstrap daterangepicker and it works if I make the change manually.

**Comment by envision** [comment]
I tried this manual fix but it didn't have noticeable effect...

Ideas on how to achieve this?
https://github.com/dangrossman/bootstrap-daterangepicker/issues/1229
