### ISSUE TITLE
About npm

### ISSUE THREAD

**Issue by x09326** [fragaria/angular-daterangepicker#198]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

I want to know whether [here](https://www.npmjs.com/package/angular-daterangepicker) is this lib.
If it is true, I will host this lib with npm auto-update config.

Thanks!
https://github.com/cdnjs/cdnjs/issues/8014

**Comment by ashsearle** [comment]
Hello,

Yes, that's the right location for this library.  I published the package there, and have now published a version with `package.json` modified to include the `npmName` and `npmFileMap` fields used by cdnjs.

Note: I have no affiliation with fragaria, and will happily hand over ownership of the package on npmjs to @krtek or another fragaria account if they ask for it.
