### ISSUE TITLE
Model not being updated:

### ISSUE THREAD

**Issue by kovan** [fragaria/angular-daterangepicker#2]
There seems to be something wrong with the ng-model binding, because my $scope model variable is not being updated, and also, adding a $watch on the variable that does nothing triggers an infinite $digest loop.

my versions are:

```
├─┬ angular-daterangepicker#0.1.1
│ ├── angular#1.2.16 (1.2.17-build.162+sha.5319621 available, latest is 1.3.0-build.2692+sha.7f5e0f0)
│ ├─┬ bootstrap#3.0.3 (latest is 3.1.1)
│ │ └── jquery#1.10.2 (2.1.1 available)
│ └─┬ bootstrap-daterangepicker#1.3.6
│   ├── jquery#1.10.2 (2.1.1 available)
│   └── momentjs#2.5.1 (latest is 2.6.0)

```

**Comment by ramprakash-ravi** [comment]
This issue still exists on v0.1.10

**Comment by krtek** [comment]
Could you please try current (0.1.12) version?

Thanks
