### ISSUE TITLE
Date&Time picker not preselected to specified input model on singleDatePicker

### ISSUE THREAD

**Issue by alexrada** [fragaria/angular-daterangepicker#200]
I'm using this directive and neither date or timepicker don't get preselected to model value. 
My model is saved as timestamp in miliseconds. Might this be an issue?

**Comment by alexrada** [comment]
So there was an issue here. I had to change the following the watch on model.startDate and model.endDate to be different when singleDatePicker is true

if (opts.singleDatePicker) {
                $scope.$watch('model', function(n) {
                return _setStartDate(n);
                });
            } else {
                $scope.$watch('model.startDate', function(n) {
                return _setStartDate(n);
                });
                $scope.$watch('model.endDate', function(n) {
                    return _setEndDate(n);
                });    
            }

**Comment by mvdam** [comment]
Thank you @alexrada you're a lifesaver! 🥇
