### ISSUE TITLE
Throws error when the model value is null

### ISSUE THREAD

**Issue by AmitMY** [fragaria/angular-daterangepicker#205]
> TypeError: Cannot read property 'startDate' of null
>     at Array.<anonymous>
>     at ngModelWatch
>     at Scope.$digest

Here are the lines:

```
  } else if (objValue.startDate) {
            return [f(objValue.startDate), f(objValue.endDate)].join(opts.locale.separator);
```

First line throws the error

**Comment by sunilkushwaha0101** [comment]
+1 am also getting this issue. anyone with the fix ?

**Comment by jdhrivas** [comment]
any updates on this issue?

**Comment by BukicMicko** [comment]
There are already issues raised for this problem.. I see that there is PR that will fix this:

https://github.com/fragaria/angular-daterangepicker/pull/136

but I don't know why it is not merged...
