### ISSUE TITLE
Can't choose 'active' date after cleaning input field

### ISSUE THREAD

**Issue by AndrusovaK** [fragaria/angular-daterangepicker#208]
Hello!

I need some help. 
I initialize single daterangepicker with minDate (start of today). 
If I clear input field using backspace or delete button, I can't choose date, that has 'active' class again.

Example: http://codepen.io/andrusova_k/pen/YWYZAG

And I can't figure out why it's happening. jQuery version of bootstrap daterangepicker hasn't this problem (example http://codepen.io/andrusova_k/pen/OXzQav).

**Comment by ypasch** [comment]
+1 Have the same issue with daterangepicker when trying to set current date for both startDate and endDate .
