### ISSUE TITLE
Start month displaying as end month and vice versa

### ISSUE THREAD

**Issue by japharr** [fragaria/angular-daterangepicker#215]
Hello,

I am having this issue, start month is been displaying as end month when the date range picker dialog is shown. I need your help guys

![screenshot_1](https://cloud.githubusercontent.com/assets/5087842/18010214/7a469090-6ba7-11e6-8eed-415e9293645b.png)

**Comment by NickLewry** [comment]
👍 having the exact same issue, it's even worse when you set `singleDatePicker: true` as the calendar opens on the month before.

**Comment by japharr** [comment]
Resolved: just found out that the css I'm using interfered with the dateranger css.
