### ISSUE TITLE
alwaysShowCalendars does not work

### ISSUE THREAD

**Issue by matthewSmithsonBCSG** [fragaria/angular-daterangepicker#217]
I can not load the page with the calendars already on display when passing this option:

`"alwaysShowCalendars": true`

as per this stackoverflow question:
http://stackoverflow.com/questions/37254625/angular-daterangepicker-always-open

This is a solution implemented for the standard jQuery version
https://github.com/dangrossman/bootstrap-daterangepicker/pull/587

If there is a simple fix please specify. Thanks

**Comment by envision** [comment]
Why wasn't this PR merged? I would be needing embedded daterange picker and there isn't many around let alone for Angular.

https://github.com/dangrossman/bootstrap-daterangepicker/pull/587
