### ISSUE TITLE
clearable="true" doesn't work in some cases

### ISSUE THREAD

**Issue by RoyXun** [fragaria/angular-daterangepicker#218]
The  jquery daterangepicker plugin removes all previously attached event handlers after  `_init` is called.  Each of the  watch listeners for `min` ,`max` and `opts` will call the `_init` function, thus the `cancel.daterangepicker` handler fails to excute when any of above watchExp changes.
So, I suppose we may bind `cancel.daterangepicker` handler in `_init` function.

**Comment by cgatesman** [comment]
The `cancel.daterangepicker` handler should be set in `_init()` if `$scope.clearable === true`--not in the `clearable` watcher.  This ensures it is always set even if `_init()` is called a second time.
