### ISSUE TITLE
range for today not working, with analysis

### ISSUE THREAD

**Issue by mirabilos** [fragaria/angular-daterangepicker#220]
Bootstrap Daterangepicker sets the default startDate and endDate to today’s start and end, making this…

```
 var thisMoment = moment();
[…]
    ranges: {
        'today': [moment(thisMoment).startOf('day'), moment(thisMoment).endOf('day')],
```

… not work (i.e. if you click on the “today” range, the field stays empty and the form not validated) because Bootstrap Daterangepicker only calls the Angular Daterangepicker-provided callback if the values actually change, nevermind that Angular Daterangepicker did not set any default values.

My current workaround is to set…

```
    startDate: moment(thisMoment),
    endDate: moment(thisMoment),
```

… in the configuration, but that’s of course not generically correct.

**Comment by maust** [comment]
I am running into the same issue without finding a workaround as I need:
- by default the startDate & endDate has to be null
- provide 'today' as predefined range
(- let the user clear both dates with cancel)

So if a user clicks on 'today' after the dates were null nothing happens the input field gets populated but the model which is bound to the daterangepicker does not get set.

If somebody found a workaround please let me know.

**Comment by maust** [comment]
There is a PR which solves it. Would be nice if it gets merged.
