### ISSUE TITLE
Date range picker start date & locale format not setting in angular view

### ISSUE THREAD

**Issue by nkdweb** [fragaria/angular-daterangepicker#221]
Hi,

Start Date & Format not setting in date range picker, please find the code below

Issue: Start date and format not bind properly in the view

**In Controller**

`$scope.pngDatePicker = { startDate: moment().subtract(1, "days"), endDate: moment() };`

  `$scope.pngDatePickerOpts = {
        locale: {
            format: 'YYYY-MM-DD'
        },
        dateLimit: {
            months: 3
        },
        maxDate: moment(),
        eventHandlers: {
            'apply.daterangepicker': function(ev, picker) {
                var sDate = $scope.pngDatePicker.startDate.format('YYYY-MM-DD');
                var eDate = $scope.pngDatePicker.endDate.format('YYYY-MM-DD');
                $scope.deliveryCenterByDate(sDate, eDate);
            }
        }
    };`

**In view**

`<input type="daterange" data-ng-required="true" date-range-picker ng-model="pngDatePicker" options="pngDatePickerOpts" id="dateRange" class="form-control date-picker">`

Output:

![datepicker](https://cloud.githubusercontent.com/assets/2375291/19068723/675fedf6-8a41-11e6-9cc1-1cbb6fb27458.jpg)

**Comment by darkray16** [comment]
It's working properly for me.
![screenshot from 2016-10-07 00 07 07](https://cloud.githubusercontent.com/assets/481132/19181459/0a8e7f9c-8c22-11e6-95c1-59a298070661.png)
