### ISSUE TITLE
Floating labels overlap date text

### ISSUE THREAD

**Issue by kroese** [fragaria/angular-daterangepicker#222]
When using this control in combination with AngularJS floating labels, after selecting the date, the text will overlap the label because the label doesn't float upwards. But if you click again inside the textbox when this happens, the label does float away and the overlap is gone.

So it seems the Daterangepicker is not generating the necessary events (like onChange) for Angular to detect that the inputbox is not empty anymore, and it will only detect the input is changed after the next click.

Does anyone how I can force this event? For example by manually firing 'onchange' from the 'apply.daterangepicker' event?

**Comment by darkray16** [comment]
Which floating labels library are  you using?  I tried loading a simple daterangepicker with https://github.com/chrisronline/angular-float-labels and it worked correctly for me?  Could you specify which library and post an example.html with the bug?

**Comment by kroese** [comment]
I'm using the ones inside the Metronic theme, I thought they were standard for the Angular Material design.

On this page: http://keenthemes.com/preview/metronic/theme/admin_1_material_design/form_controls_md.html  you can see them on the right side.
