### ISSUE TITLE
TypeError: Cannot read property 'startDate' of null

### ISSUE THREAD

**Issue by BukicMicko** [fragaria/angular-daterangepicker#223]
I see that there is open issue for this problem:

https://github.com/fragaria/angular-daterangepicker/pull/136

So why you guys don't merge this? Is there some other fix for this?

**Comment by barbossa** [comment]
+1

**Comment by realcreator** [comment]
+1

**Comment by tomergev** [comment]
+1

**Comment by SaiPhaniKnappily** [comment]
+1

**Comment by HGeo** [comment]
+1

**Comment by oles-bolotniuk** [comment]
Issue still exists because this lib isn't maintained.
In our project I fixed this by exposing model **date** and **options** objects to the controller scope:

**View:**
```
<div
  date-range-picker
  ng-model="date"
  options="options"
></div>
```

**Controller**:
```
$scope.options = {
  showDropdowns: true,
  opens: 'left',
  drops: 'down',
  applyClass: 'btn-primary'
};

$scope.date = {
  startDate: moment(),
  endDate: moment()
};
```
