### ISSUE TITLE
Multiple date formats are ignored

### ISSUE THREAD

**Issue by chrisparton1991** [fragaria/angular-daterangepicker#225]
Hi,

I'm experiencing an issue where I have a single date field and a single datetime field. The two fields use different locale formats, but when both exist on the page, the second format overrides the first.

This could be a duplicate of another open issue, but it's difficult to tell.

CodePen: http://codepen.io/chrisparton1991/pen/eBOVEG
Note that the date field does not have the correct format applied. Commenting out the HTML for the datetime field resolves the issue.

**Comment by jeeshenlee** [comment]
Is this issue resolve? I'm experiencing the same problem when I have two daterangepicker on the same page.
