### ISSUE TITLE
autoUpdateInput is set to false by default in the _init() but should be true?

### ISSUE THREAD

**Issue by tapashya** [fragaria/angular-daterangepicker#230]
Hello,
In the angular wrapper the logic that initialises the daterangepicker has the option **autoUpdateInput** set to **false** by default so updating the start and end date programmatically from the angular controller does not update the actual input field in the view. Also when specifying the locale format for the dates, on first load this format is not applied because of the same reason as the **updateElement()** function in the bootstrap daterangepicker code required this setting to be true to update the input.
I tried changing this setting to true in the angular wrapper and both my issues above are solved i.e the locale format is correctly applied on first load and also while programmatically updating the start and the end date, the input is updated but I am not sure if anything else might be affected because of this change?Please advise.
Thanks

**Comment by tapashya** [comment]
After a closer look, it looks like flipping the default options and the options passed in the _init() would do the job if autoUpdateInput needs to be false for other reasons, so instead of

 _init = function() {
          var eventType, results;
          el.daterangepicker(angular.extend(opts,{
              autoUpdateInput: false
          }), function(start, end) {

it could be...

 _init = function() {
          var eventType, results;
          el.daterangepicker(angular.extend({
              autoUpdateInput: false
          },opts), function(start, end) {

**Comment by arboshiki** [comment]
I have exactly the same problem. 
Where have you done this? In your own fork? Have you made a pull request?
