### ISSUE TITLE
Cannot select today date when there is only min date validation

### ISSUE THREAD

**Issue by BukicMicko** [fragaria/angular-daterangepicker#231]
When there is only min validation for the first time I cannot select today date. If I choose another date first then I can choose today date. 

`<input date-range-picker id="carRecDate" class="form-control date-picker" type="text" data-ng-model="carvm.eventObj.carReceivedDt" placeholder="mm/dd/yyyy" options="{locale:{format: 'MM/DD/YYYY'}, singleDatePicker:true}" min="carvm.review.reportSentDt" max="carvm.todayDate" />`

`<input type="text" id="revResDate" class="form-control datepicker" min = "carvm.eventObj.carReceivedDt" placeholder="mm/dd/yyyy" date-range-picker data-ng-model="carvm.eventObj.revisedResponseDt" options="{locale:{format: 'MM/DD/YYYY'}, singleDatePicker:true, drops: 'up'}" required/>`

For second datepicker i cannot choose today date for first time. Nothing happens when click on today date. Even watcher for this model in controller is not fired up. If I add for example max="carvm.todayDate()" then I can choose today date for first time.

Any ideas?

**Comment by crysthofferattier** [comment]
did you fix this problem? I'm having the same issue

**Comment by BukicMicko** [comment]
@crysthofferattier no.. still issue for me. I see that lately many issues are raised and none are even discussed .... it is getting bad.

**Comment by crysthofferattier** [comment]
@BukicMicko thanks for answering me

**Comment by tomergev** [comment]
+1
