### ISSUE TITLE
Not working inside ngDialog

### ISSUE THREAD

**Issue by rahmonov** [fragaria/angular-daterangepicker#232]
It is working fine on other pages except for inside ngDialog.

Getting this error:

`angular.js:13920 TypeError: el.daterangepicker is not a function`

Any idea what could be the problem?

**Comment by maximelafarie** [comment]
Piece of code ?

**Comment by sairam** [comment]
happens when bootstrap daterangepicker is not added as a resolver. (happened with webpack config). i was using the older version of this. i had to add moment as an explicit dependency. via imports loader.

**Comment by rahmonov** [comment]
sorry about this, it was my bad. There was a script that tries to optimize script loading. It was messing things up.
