### ISSUE TITLE
getting "Cannot set property 'date' of undefined" error 

### ISSUE THREAD

**Issue by narsignt** [fragaria/angular-daterangepicker#233]
Hi,

I am using bower to install packages. When i installed in my html file and i included directive like below

html file
<input date-range-picker class="form-control date-picker" type="text" ng-model="datePicker.date" />

js file
            var date = moment(),
            endDate=moment(date).endOf('week'),
            starDate=moment(endDate).subtract(2, 'months').startOf('week'),
            $scope.datePicker.date={startDate:starDate,endDate:endDate};

i am gettting below error

angular.js:13920TypeError: Cannot set property 'date' of undefined
    at new <anonymous> (calendarTableInput.html?_ijt=pg5hkgcscdp0f5opjipblpbolu:59)
    at Object.invoke (angular.js:4718)
    at S.instance (angular.js:10354)
    at p (angular.js:9263)
    at g (angular.js:8620)
    at angular.js:8500
    at angular.js:1763
    at m.$eval (angular.js:17682)
    at m.$apply (angular.js:17782)
    at angular.js:1761

Could anyone help on this.

Thanks,
Narsi.

**Comment by smnedelko** [comment]
Hi, the `$scope.datePicker` obj is not exist, so instead of 

`$scope.datePicker.date={startDate:starDate,endDate:endDate};`

use

`$scope.datePicker = { date: {startDate:starDate,endDate:endDate} };`
