### ISSUE TITLE
Option "separator" doesn't work.

### ISSUE THREAD

**Issue by luizfilipe** [fragaria/angular-daterangepicker#234]
I'm trying to replace the dash by a "to" word between the dates but this seems does not work.

Follow below the way that I'm using on the html input tag.

```
<input class="form-control date-picker"
                           type="text"
                           name="design"
                           id="design"
                           ng-model="modal.design"
                           date-range-picker
                           options="{separator: 'to', locale: {format: 'MM/DD/YYYY'}, parentEl: 'div#design-container'}"/>
```

**Comment by anurag619** [comment]
I found a temporary solution for adding you desired separator. Just open the source file and in the first line you will find 'locale:{separator: ', in the key add your separator.

**Comment by maximelafarie** [comment]
Don't change anything in the plugin source code, that's not necessary.
Separator has to be nested in locale object. So you should have something like this: 
```
{
  locale: {
    separator: 'to',
    format: 'MM/DD/YYYY'
  },
  parentEl: 'div#design-container'
}
```

**Comment by anurag619** [comment]
Thanks, that works.

**Comment by luizfilipe** [comment]
So the README should be fixed...

**Comment by maximelafarie** [comment]
I just made a PR. But the project hasn't been updated since 7 months so I think we have to wait a bit.

**Comment by luizfilipe** [comment]
Sweet
