### ISSUE TITLE
Cannot apply default values after clearing calendar

### ISSUE THREAD

**Issue by de-ocampo** [fragaria/angular-daterangepicker#243]
This can be observed on the demo calendars that are up. Reproduce as follows:

1. Clear a date.
2. Click on date picker. Default date is visible.
3. Click apply.

Behavior: No date is applied unless the date is changed to something else and changed back. The input field is left blank.
Expected: The date is set even after clearing.

After clearing the picker appears to listen for a change in date and appears unable to display the existing date range any longer until you change it to something else and change it back.

**Comment by jeetudon** [comment]
Same problem with custom range
