### ISSUE TITLE
Today date or already selected date on previous input cant able to select

### ISSUE THREAD

**Issue by venkat2384** [fragaria/angular-daterangepicker#249]
Hi,

I am using Daterangepicker for our application.

Creating multitrip date picker component (3 input fields)

1. TripOne - Select date (Ex: 19th Feb)
2. TripTwo - Have to start from 'TripOne' selected date.
3. TripThree - Have to start from 'TripTwo' selected date.

Above things are working fine. But, below issue not working on this plugin.

1. TripOne - Select Today date (Not working)
2. TripTwo - If Feb 20th selected on TripOne, i cant able to select same Feb 20th on TripTwo.
3. TripThree - Similar to TripTwo.

Please need some one guidance or help to solve this issue ASAP.

[https://jsfiddle.net/jkenluv/z9tgdh7k/4/](url)

Thanks

**Comment by w-A-L-L-e** [comment]
We have the same issue as described in 1, most features work except selecting 'today' as first selection. What's odd is you can first select another day then close it, open up and then selecting 'today' works again... This also happens with ranges and datetimes...
