### ISSUE TITLE
Bundle

### ISSUE THREAD

**Issue by SduyXD** [fragaria/angular-daterangepicker#25]
can you do a bundle with the dependencies and angular-date-rangepicker?

**Comment by krtek** [comment]
Hello. 

You mean a **zip** file with all dependencies? Well I could do that... 



—

**Comment by SduyXD** [comment]
Yes but in a .js file something like: "angular-daterangepicker-bundle.js"

**Comment by krtek** [comment]
Hello. 
I decided not to provide such bundle as I feel that bower should be preffered way to get the package with all deps. Still, you can [download individual releases](https://github.com/fragaria/angular-daterangepicker/releases) (without deps)..
