### ISSUE TITLE
Showing selected range label

### ISSUE THREAD

**Issue by guilleferrer** [fragaria/angular-daterangepicker#251]
When a range is selected ( e.g. "Today" ) , I would like to show "Today" instead of the daterange ( from - to ).

I expected 'apply.daterangepicker' to show wheter a custom range had been selected, but I can only access to the "model".

Is there any way to access to the range "label" information when applying ?

Thanks!

**Comment by Nico-Daco** [comment]
line 145 --> 151 in [this file](https://github.com/fragaria/angular-daterangepicker/blob/master/js/angular-daterangepicker.js) add **picker** 
``
eventHandlers: {
                'apply.daterangepicker': function selected_date(e, picker){
                  console.log(picker)
                 }
}
``
``
for (eventType in opts.eventHandlers) {
  results.push(el.on(eventType, function(e,**picker**) {
    var eventName;
    eventName = e.type + '.' + e.namespace;
    return $scope.$evalAsync(opts.eventHandlers[eventName],**`picker`**);
  }));
 }
``

You can now catch the selected range
