### ISSUE TITLE
How do I get the literal date

### ISSUE THREAD

**Issue by Cranavvo** [fragaria/angular-daterangepicker#256]
How do I get the literal date from the model?

It is pushed to the model as an object?

**Comment by gnutix** [comment]
@connor-simpson  ![wisdom_of_the_ancients](https://user-images.githubusercontent.com/310134/195398143-a0ef89f3-5d82-4b7a-bd61-2c67df7ed0b6.png)

**Comment by connor-simpson** [comment]
@gnutix I can't believe I didn't see this sooner.

What a wild time of my life at _that_ place!
