### ISSUE TITLE
Distinct Instances of Date Range picker share same config

### ISSUE THREAD

**Issue by elm-** [fragaria/angular-daterangepicker#26]
I have a problem when using the date range picker in two different combination, once with single date and once with date range. Both are in two different pages (even popups). When using any one individually it works, however. When first using the single date picker and then navigating to a page with the date range picker, only a single date drop down is shown. Somehow there seems to be a global state that is not reset.

Happens on all browsers and latest angular-daterangepicker version.

Any idea where to start looking for this? as we use the component directly I do not see how this can be coming from any configuration we do, looks like something that is not reset from a global daterangepicker setting?

**Comment by jim-mackenzie** [comment]
I just downloaded this today and am finding similar issues.  Everything seems to be shared between multiple instances.  I'm using $watch to get when the field changes.

I've got ranges, "Yesterday" "Today" "Last 7" "Last 30".  If I go to one screen and click on Today.  The dates are filled in on the form, and the $watch executes perfectly.

If i then go to a completely different screen, bring up the calendar, first off, Today is already highlighted, and if I click Today, it fills in the dates on the form, but the $watch does NOT fire.

This is a huge problem.
