### ISSUE TITLE
date range format is not working

### ISSUE THREAD

**Issue by prashant93** [fragaria/angular-daterangepicker#262]
Hi I have applied date format as YYYY-MM-DD(screen shot 1) it's working but it's not working when applied 
MM-DD-YYYY(screen shot 2).

My conclusion is only YYYY-MM-DD format is only working. I tried but not figured the issue.

![image](https://cloud.githubusercontent.com/assets/4151470/25527951/dc05b804-2c38-11e7-8d45-893c83f3efaf.png)

![image](https://cloud.githubusercontent.com/assets/4151470/25527926/bcab0428-2c38-11e7-9ab8-f333bb2d2d91.png)

**Comment by riteshthakur** [comment]
$scope.opts = {
        autoApply: true,
        locale: {
            
            applyClass: 'btn-green',
            applyLabel: "Apply",
            fromLabel: "From",
          #   **_format: "MM-DD-YYY",_**
            toLabel: "To",
            cancelLabel: 'Cancel',
            customRangeLabel: 'Custom range'
           
        }

you can try this 1...
