### ISSUE TITLE
how to solve this problem?

### ISSUE THREAD

**Issue by costel-petrescu** [fragaria/angular-daterangepicker#263]
Hi.
I've a question. There are four pages that be connected to each other and there are date-range-pickers on each pages. when i change the period of it on first page, how can i do to show the same periods on other pages?

Thanks.

**Comment by droyson** [comment]
If you have a common controller for all four pages, then you can just initialize same date object in common controller for all four pages.

**Comment by costel-petrescu** [comment]
of course, I've defined a common controller for all pages. The problem is that when i change the period of one date-range-picker, the change is shown in the calendar, but it's not displayed in a input-box.
what's the reason?

**Comment by droyson** [comment]
Could you share the code or an example.
