### ISSUE TITLE
autoUpdateInput always overwritten

### ISSUE THREAD

**Issue by sunny-kashyap** [fragaria/angular-daterangepicker#273]
in _init
line no. 135 
el.daterangepicker(**angular.extend(opts, {
            autoUpdateInput: false
          }**), function(start, end) {
            return $scope.$apply(function() {
              return $scope.model = opts.singleDatePicker ? start : {
                startDate: start,
                endDate: end
              };
            });
          });
here it always overwrite value to false for autoUpdateInput field. Thats why when we change it from daterangepicker from single picker then it doesnot update the input value.

**Comment by Francois-du-Plessis** [comment]
Also getting this issue. Cannot see a reason for forcing autoUpdateInput to false as it does not affect the model.
