### ISSUE TITLE
Directive is not working when using minified file

### ISSUE THREAD

**Issue by HarelM** [fragaria/angular-daterangepicker#28]
Hi, I'm getting the below error when using the minified file.
I'm guessing it has to do with the directive initialization injection list that is not using strings and relies on variables names.
am I the only one who experience this?
using the full (not minified) version works as expected (except for know issues described here on github).

Thanks,
Harel M.

Error: [$injector:unpr] Unknown provider: tProvider <- t <- dateRangePickerDirective
http://errors.angularjs.org/1.3.8/$injector/unpr?p0=tProvider%20%3C-%20t%20%3C-%20dateRangePickerDirective
    at REGEX_STRING_REGEXP (angular.js:63)
    at angular.js:3994
    at Object.getService [as get] (angular.js:4141)
    at angular.js:3999
    at getService (angular.js:4141)
    at Object.invoke (angular.js:4173)
    at angular.js:6482
    at forEach (angular.js:323)
    at Object.<anonymous> (angular.js:6480)
    at Object.invoke (angular.js:4182)

**Comment by HarelM** [comment]
I've changed the following line in the non minified file:
<code>picker.directive('dateRangePicker', function($compile, $timeout, $parse, dateRangePickerConfig) {</code>
to:
<code>picker.directive('dateRangePicker', [ "$compile", "$timeout", "$parse", "dateRangePickerConfig", function($compile, $timeout, $parse, dateRangePickerConfig) {</code>
and minified the file. this seem to work and solved the issue.

Can you please commit this change?

**Comment by krtek** [comment]
Hello,

it should be fixed in 0.1.12.

Thanks,
Lukas
