### ISSUE TITLE
Model is not updating

### ISSUE THREAD

**Issue by losp1001** [fragaria/angular-daterangepicker#280]
Hello, im having ploblems using this library, for example if you want to update the startDate or endDate from the scope, it doesn't change, just change input contain but model is the same before change the dates, someone can help me to fix this issue??

**Comment by d4guru** [comment]
same issue with all the directives I have tried !!!

**Comment by vamsikrishnamannem** [comment]
For me also, the Same problem. Is there any temporary solution?

**Comment by AymanNatsheh** [comment]
I faced the same issue and did this to overcome it: 
1. Assign a new moment object to startDate or endDate. If you try to change on the existing model, it will not trigger the needed watchers as expected. 
2. after doing point 1, make sure to add a timeout before opening the datereangepicker. in my case, i was triggering it pragmatically. 

hope it helps.

**Comment by cgatesman** [comment]
@AymanNatsheh, the trick for me was actually creating an entirely new `$scope.dateRange` object.  Just changing the `startDate` or `endDate` properties do not trigger a change.
