### ISSUE TITLE
Calendar Issue

### ISSUE THREAD

**Issue by JaewoongShin** [fragaria/angular-daterangepicker#286]
Hey guys,
I think I found one issue.
1. When using Custom Range with begin date and end date in the calendar.
  a. Select any begin date in the left calendar (e.g.: 2/28/2018)
  b. Click on the '>' button in the right calendar to select later end date (e.g. 12/31/2018)
  c. Then begin date is changed automatically to weird date even if I set dateLimit property to months: 12
    
However, Functionality itself is working, but front-end part is not working correctly. This seems like only front-end issue in the calendar which makes end users confused.

**Comment by amit777** [comment]
Hi, are you seeing an incorrect date range in the boxes even though the angular scope object start and end dates look correct?  I'm having the same issue.
