### ISSUE TITLE
Date is empty when initially clicked on 'Today' which is already selected.

### ISSUE THREAD

**Issue by BMK91** [fragaria/angular-daterangepicker#288]
When I'm set initial model value to NULL, input filed is empty.
Predefined range "Today" is selected as default and you CAN'T click on today.
If you click on some other predefined range everything will work.
When I clear the field with "clearable" functionality, field get's default value and again selected predefined value is "Today" and you can't click on it.

Is there some solution for setting initial value to NULL and clearing field to NULL ?

**Comment by sonnd92** [comment]
I face to same issue. Someone can give a solution.

**Comment by PranavBhatia** [comment]
Same issue, is anyone working on this one?
