### ISSUE TITLE
Should not allow user to edit start date and end date in input text box

### ISSUE THREAD

**Issue by ramprakash-ravi** [fragaria/angular-daterangepicker#30]
How can we make input box of start and end date to be readonly ?

**Comment by ashrith-flipkart** [comment]
+1 for this feature. It should be configurable field individually.

**Comment by richadams8** [comment]
Bit of a hack, but I just hid it and set it to readonly

```
<label>
    <i class="fa fa-calendar-o"></i>
    {{ startText + ' - ' + endText }}
    <i class="fa fa-angle-down"></i>
    <input date-range-picker="opts"
           type="text"
           ng-model="dateRangeProtected"
           max="currentDate"
           min="smallestDate"
           options="opts"
           readonly>
  </label>
```

but I also wrapped it in a directive to get some consistent use out of it.  It also seems to have a problem with the output coming out of it sometimes being a Date and other times being a Moment.  And that whole date-range-picker="opts" fixed something for us too... cant remember what right now.

**Comment by empirecoder** [comment]
+1 thx

**Comment by dsbaars** [comment]
+1, also external trigger to activate the widget would be useful here.

**Comment by AlenkaM** [comment]
+ 1

**Comment by 284247028** [comment]
+1
