### ISSUE TITLE
Initialize with a default date when singleDatePicker set true

### ISSUE THREAD

**Issue by thonythony** [fragaria/angular-daterangepicker#37]
Hi,

When I attempt to set a default date (contained in my scope like $scope.date) with the option singleDatePicker set to true, the plugin don't handle the date and display the current date.
Otherwise, this functionality works correctly when the option  singleDatePicker is set to false.
Anyone know why ?

Thanks

**Comment by z0ran8** [comment]
I have the same problem. Did you find a solution by any chance @thonythony ?

**Comment by raygerrard** [comment]
The current behaviour is that when setting singleDatePicker to true the data still has to be an object that contains a startDate e.g.

    $scope.date = {
        startDate: "01/01/2000",
        endDate: null
    };

See proposed change: https://github.com/fragaria/angular-daterangepicker/issues/114
