### ISSUE TITLE
Daylight savings offset error

### ISSUE THREAD

**Issue by KurtPreston** [fragaria/angular-daterangepicker#38]
If a date is selected that has a different UTC offset, the date will be improperly set.  This is mainly evident if you select a date before daylight savings time went into affect.

Example:
Select the range "Mar 1" to "Mar 1" using the calendar.  After you hit apply, the date range will change to "Feb 28" to "Mar 1".

This issue does not appear with the vanilla bootstrap-daterangepicker.

**Comment by richadams8** [comment]
+1

**Comment by covus-benjamin-schuch** [comment]
+1

**Comment by sylvainbannier** [comment]
+1

**Comment by sufleR** [comment]
+1

**Comment by idahotallpaul** [comment]
There appear to still be daylight saving time issues present. Using the example.html code, I run into this:

Example 1: This all works as expected.
* Select a date range of ```June 1, 2015 to June 1 2015```
* The date picker displays the correct dates. 
* Output for that date object is: ```{"startDate":"2015-06-01T06:00:00.000Z","endDate":"2015-06-02T05:59:59.999Z"}```. 
* Create a new date from that start date (```$scope.testDate = new Date($scope.date2.startDate);```)
* Pipe it to a date in the template ```{{testDate | date}}``` 
* The output is ```Jun 1, 2015```

Example 2: The start date is wrong for dates outside of daylight savings time.
* Select a date range of ```December 31, 2015 to December 31 2015```
* The date picker displays the correct dates. 
* Output for that date object is: ```{"startDate":"2015-12-31T06:00:00.000Z","endDate":"2016-01-01T05:59:59.999Z"}```. 
* Create a new date from that start date (```$scope.testDate = new Date($scope.date2.startDate);```)
* Pipe it to a date in the template ```{{testDate | date}}``` 
* The output is ```Dec 30, 2015 ```

The time offset for the dates is the same, even though one date is in DST and the other is not. There appears to be time zone compensation happening in the date picker display but not in the date picker data. My assumption would be that the displayed date would match the date data regardless of what day of the year is selected.
