### ISSUE TITLE
The date picker can be later customized by passing options attribute.

### ISSUE THREAD

**Issue by mathiasewald** [fragaria/angular-daterangepicker#41]
Readme states "The date picker can be later customized by passing options attribute." Can somebody post a working example?

**Comment by borodean** [comment]
Works well in 1.3.18, but stopped to in 1.3.19 of https://github.com/dangrossman/bootstrap-daterangepicker.

**Comment by borodean** [comment]
...or not, hmm. Well, at least I'm the one who is also experiencing this issue. @fragaria, can I help you with this anyhow?

**Comment by storrisi** [comment]
Can't get it work too, if i set an options param with ranges defined, nothing happens

**Comment by jimmyt1988** [comment]
Agreed, i'd love an example!

**Comment by Narxivias** [comment]
Having the same issue here, I'm trying to use the option "locale" to localize the labels and nothing seems to work. 

After reading @borodean suggestion, both version 18 and 19 seems to not give any way to use the options.
