### ISSUE TITLE
TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by satan1999** [fragaria/angular-daterangepicker#43]
Hi There

I got the following js error when closing Dialog(Modal) 

TypeError: Cannot read property 'remove' of undefined
    at angular-daterangepicker.min.js?compile=false:1

Just wondering if you know how to get around this

Cheers
Wallace

**Comment by tbugrara** [comment]
Seems like this was fixed in #35, but there is no tag for this fix so bower doesn't pull in latest. Could we get a new release?

**Comment by krtek** [comment]
Should be released already.
