### ISSUE TITLE
Can not customize the format of the date in the input field

### ISSUE THREAD

**Issue by satan1999** [fragaria/angular-daterangepicker#44]
Hi There

I tried with the sample of customising format of date. Which didn't work for me .

 <input date-range-picker class="form-control date-picker" type="text"
                           name="date2" ng-model="date2" options="{format: 'MMMM D, YYYY'}" required/>

Cheers
Wallace

**Comment by gpicazo** [comment]
Custom formats seem to be working, but only after a date is manually chosen, not with the default date though. The same is true about the separator option.

**Comment by gpicazo** [comment]
Seems to work if I change line 150 as shown below. I've not done a lot of testing though.

if (attrs.options) {                                                                                   // 147
          $scope.$watch('opts', function(newOpts) {                                                            // 148
            opts = angular.extend(opts, newOpts);                                                              // 149
            return _init();                                                                                    // 150
          });                                                                                                  // 151
        }

to

if (attrs.options) {                                                                                   // 147
          $scope.$watch('opts', function(newOpts) {                                                            // 148
            opts = angular.extend(opts, newOpts);                                                              // 149
            return modelCtrl.$render();                                                                                    // 150
          });                                                                                                  // 151
        }

**Comment by aguerre** [comment]
@gpicazo I've exactly this issue. predefined ranges cause "Invalid date" because of wrong format in input...

**Comment by aguerre** [comment]
@satan1999  just realized that you have to write  `options="{locale: {format: 'MMMM D, YYYY'}}"`

But my problem is still here....

**Comment by nickroberts** [comment]
I am seeing the same issue. I would like the model value to be what format I select, not just the display. Is this possible?
