### ISSUE TITLE
ng-model not updated

### ISSUE THREAD

**Issue by storrisi** [fragaria/angular-daterangepicker#45]
It seems that the ng-model, defined to start the directive, is not bind on change of the date.
It should need an hack to get it work?

Thank you

**Comment by mroswald** [comment]
try using a ng-model name with a dot in it like mydatepicker.date

**Comment by nmeln** [comment]
@krtek Could you add mroswald's tip to README please? 
I tried to follow the example, but model didn't get updated until I've put a dot in it.
I don't know why the directive behaves like that.

**Comment by krtek** [comment]
Ok, will do. 
See [this SO answer](http://stackoverflow.com/questions/18128323/angularjs-if-you-are-not-using-a-dot-in-your-models-you-are-doing-it-wrong) and [AngularJS docs](https://github.com/angular/angular.js/wiki/Understanding-Scopes) for explanation.
