### ISSUE TITLE
Model doesn't update for current day

### ISSUE THREAD

**Issue by PhilBroadbent** [fragaria/angular-daterangepicker#46]
Hi,

Either selecting todays date on both datepickers, or clicking 'today' (essentially the same thing) does not seem to update the model.

I can select any other day or range (including today) and it updates.

Any idea why please?

Thanks.

**Comment by renus1** [comment]
I am facing the same issue. please let me know when it will be resolved. thank you.

**Comment by vascofg** [comment]
+1

**Comment by petarslovic** [comment]
+1

**Comment by krtek** [comment]
Does it occur in 0.1.15?

**Comment by petarslovic** [comment]
I found this to be a problem only when initial dates were set to null (so that start date and end date would be empty), and then selecting the today's date wouldn't update the model. However, if you selected a date different than today (which would update the model) and then select the today's date, the model would be updated.

I cannot confirm if it's still happening because of #67 - it doesn't allow us to set empty initial dates anymore.

**Comment by saurabh-agrawal83** [comment]
+1

**Comment by captplanet** [comment]
+1, selecting today's date for both start and end date does not set the model.

**Comment by petarslovic** [comment]
Just an update, this is still a problem in 0.1.16.

**Comment by captplanet** [comment]
Has this issue been addressed yet?

**Comment by ddctd143** [comment]
Still have this issue

**Comment by tomahim** [comment]
Facing this issue again

**Comment by esx2ve** [comment]
It's a problem with the inner jQuery plugin.
Just fix it like like this:

// fix a bug with selecting 'today'
            $("input[date-range-picker]").data().daterangepicker.oldEndDate = null;
            $("input[date-range-picker]").data().daterangepicker.oldStartDate = null;

**Comment by captplanet** [comment]
Where exactly would that code go in the jQuery plugin?

**Comment by nmeln** [comment]
@esx2ve Where have you put that code in?

**Comment by lucasrsantos1** [comment]
I am not sure if this is the proper way to do it but I created a new directive and added @esx2ve 's code and it worked.
Here's the code: 

  .directive('fixdatepicker', function($timeout) {
    return {
      restrict: 'A',
      link: function(scope, element, attr){
        $timeout(function() {
          $(element).data().daterangepicker.oldEndDate = null;
          $(element).data().daterangepicker.oldStartDate = null;
        }, '500')
      }
    }
  })

**Comment by Wlada** [comment]
This solution doesn't work for me. Does someone have solution?

**Comment by lucasrsantos1** [comment]
The code I posted above works perfectly fine for me. You just have to add 'fixdatepicker' to your datepicker html.

**Comment by Wlada** [comment]
I found solution for my situation, it's similar

     .directive('fixNullDatepicker', function($timeout) {
            return {
                restrict: 'A',
                link: function(scope, element, attr){
                    var $element  = $(element);
                    $element.data().daterangepicker.oldEndDate = null;
                    $element.data().daterangepicker.oldStartDate = null;

                    $element.on('show.daterangepicker', function (ev, picker) {
                        var l = $element.val().trim().length;

                        if (l < 1) {
                            $(document).find('.daterangepicker .ranges li').removeClass('active');

                            $element.data().daterangepicker.oldEndDate = null;
                            $element.data().daterangepicker.oldStartDate = null;
                        }
                    });
                }
            }
        })

**Comment by gsamba92** [comment]
I had the same problem. My initial dates were set to null but setting "$element.data().daterangepicker.oldEndDate = null" and
"$element.data().daterangepicker.oldStartDate = null"
used to break my clear button and the calendar used to stop working. So i wrote the below  solution and to set the old dates to null only when the show calendar event was triggered and the apply button was clicked for the current day. It worked for me and its a slight modification of @Wlada 's code

.directive('fixNullDatepicker', function($timeout) {
return {
restrict: 'A',
link: function(scope, element, attr){
$timeout(function() {
$element.on('show.daterangepicker', function (ev, picker) {
                   $(document).find('.daterangepicker .ranges li').removeClass('active');
                   $('.applyBtn').on('click',function(event){
                   var l = $element.val().trim().length;

                    if (l < 1 && $element.data().daterangepicker.oldEndDate != null && $element.data().daterangepicker.oldStartDate != null) {
                        
                        var start = $element.data().daterangepicker.oldStartDate.format('MMM Do YY');
                        var end = $element.data().daterangepicker.oldEndDate.format('MMM Do YY');
                        var current = moment().format('MMM Do YY');
                        
                        if(start == current && end == current){
                          
                        $element.data().daterangepicker.oldEndDate = null;
                        $element.data().daterangepicker.oldStartDate = null;
                          
                        }

                    }  
                     
                   });
                   
                });
}, '500');
}
}
})

**Comment by ajzawawi** [comment]
@PhilBroadbent Accidentally closed this, please feel free to re-open. I'll be submitting a PR to fix this issue shortly.

**Comment by reda-alaoui** [comment]
@ajzawawi , the PR has been waiting there https://github.com/fragaria/angular-daterangepicker/pull/177 since March 2016.
Can you merge it please?
