### ISSUE TITLE
Date vs. Moment object in watch function

### ISSUE THREAD

**Issue by danielmcquillen** [fragaria/angular-daterangepicker#49]
Hi,

Thanks for the awesome library. However, I'm confused about the data returned in the $watch function as shown in the example.

Before when I used daterangepicker by itself in my pre-Angular days, the daterangepicker callback would provide me with Moment objects. 

However, when I've set things up per the example in this repo, the start and end dates in the callback are only Date objects.

Is there a way to configure angular-daterangepicker so that it returns Moment objects set to the correct UTC? 

Thanks for any thoughts.

**Comment by richadams8** [comment]
I noticed a similar problem.  It seemed like the first time that it ran it gave me back a Date object, but then when I selected something a Moment came back.  I got around this and the dst issue by watching the returned values from the angular-daterangepicker and constructing moments from them to make sure that the values I was getting were moments.

eg.

```javascript
var updateDates = function(newVal, oldVal) {
  if (newVal !== oldVal) {
    // hack to deal with dst problem
    var computeBegin = moment(newVal.startDate).add(2, 'hours').startOf('day');
    var computeEnd = moment(newVal.endDate).endOf('day');
    $scope.dateRange = {
      startDate: moment(computeBegin).utc(),
      endDate: moment(computeEnd).utc()
    };
  }
};

$scope.$watch('dateRangeProtected', updateDates);
```

Admittedly hacky, but it dealt with some issues that I was having with the output from the daterangepicker being inconsistent.

**Comment by maxm450** [comment]
Same issue
