### ISSUE TITLE
td min-width prevents resizing calendar

### ISSUE THREAD

**Issue by whitej8** [fragaria/angular-daterangepicker#52]
.daterangepicker .calendar th, .daterangepicker .calendar td has a min-width applied.  This prevents the overall width of the calendar from shrinking as needed overriding this solved my issue

.daterangepicker .calendar th, .daterangepicker .calendar td { min-width: 100% !important; }

**Comment by krtek** [comment]
Hello, 
I believe that this issue belongs to [Bootstrap Datepicker](https://github.com/dangrossman/bootstrap-daterangepicker).
