### ISSUE TITLE
Date picker localization via angular-translate

### ISSUE THREAD

**Issue by issoft-nsiniakevich** [fragaria/angular-daterangepicker#55]
Trying to localize daterangepicker via angular-translate.

Basically it's look like:

**View**
```
<input date-range-picker 
   class="form-control date-picker" type="text" 
   ng-model="date" options="opts"/>
```

**Controller**
```
var localizedRanges = {};
localizedRanges[$translate.instant('TODAY')] = [moment(), moment()];

$scope.opts = {
    locale: {
        applyLabel: $translate.instant('APPLY'),
        daysOfWeek: $locale.DATETIME_FORMATS.SHORTDAY,
        monthNames: $locale.DATETIME_FORMATS.MONTH
    },
    ranges: localizedRanges
};
```
It works very well, but if I change language, datepicker is still on previous language. If I reload page it will show datepicker on the right language.

I find out that I can subscribe on $translateChangeSuccess event:

```
$rootScope.$on('$translateChangeSuccess', function () {
//reinitialize datepicker
});
```

So, I'm looking for refresh/reinitialize datepicker mechanism at runtime.
Any ideas how to do that?

**Comment by issoft-nsiniakevich** [comment]
Well, I will answer to myself.

Data range picker has a watcher on options:
```
$scope.$watch('opts', function(newOpts) {
    opts = angular.extend(opts, newOpts);
    return _init();
});
```

In controller just simply update options in the event handler:
```
$rootScope.$on('$translateChangeSuccess', function () {
  $scope.opts = {
    locale: {
        applyLabel: $translate.instant('APPLY'),
        ...
    }
  };
});
```

Regarding the $locale service, I use [angular-dynamic-locale](https://github.com/lgalfaso/angular-dynamic-locale)
(Here the example)[https://scotch.io/tutorials/internationalization-of-angularjs-applications] how to link angular-translate with angular-dynamic-locale

After that we can subscribe on `$localeChangeSuccess` event:
```
$scope.$on('$localeChangeSuccess', function() {
  $scope.opts = {
     locale: {
       daysOfWeek: $locale.DATETIME_FORMATS.SHORTDAY,
       monthNames: $locale.DATETIME_FORMATS.MONTH
     }
  };
});
```

**Comment by fresh-mind** [comment]
Thank you for your answer to yourself, very helpful info.
