### ISSUE TITLE
need handle event in angular way

### ISSUE THREAD

**Issue by belerweb** [fragaria/angular-daterangepicker#56]
There are events(show.daterangepicker/hide.daterangepicker/cancel.daterangepicker) in daterangepicker. If we don't use angular, we can use code:
``` javascript
$('#daterange').on('cancel.daterangepicker', function(ev, picker) {
  //do something, like clearing an input
  $('#daterange').val('');
});
```

But we are using angular, we use should write code like $scope.$on('cancel.daterangepicker', ...).

So, please consider event hanlder integration.

**Comment by krtek** [comment]
+1 for this :) This would be really nice feature.

**Comment by belerweb** [comment]
@krtek You are so nice. :) Thanks.

**Comment by himanshugoyal5734** [comment]
can you tell me fire an event on apply function in angular js????
