### ISSUE TITLE
Bad Tag Release 0.1.13 - Code is old?

### ISSUE THREAD

**Issue by mtraynham** [fragaria/angular-daterangepicker#57]
Since I have patch releases enabled, ~0.1.13 got picked up.  

The Tag 0.1.13 has quite a few code differences from Master even though it is 0 commits behind:
https://github.com/fragaria/angular-daterangepicker/blob/master/coffee/angular-daterangepicker.coffee#L100
https://github.com/fragaria/angular-daterangepicker/blob/0.1.13/coffee/angular-daterangepicker.coffee#L116

https://github.com/fragaria/angular-daterangepicker/blob/master/js/angular-daterangepicker.js#L105
https://github.com/fragaria/angular-daterangepicker/blob/0.1.13/js/angular-daterangepicker.js#L130

Original error from console:
```
TypeError: Cannot read property 'endDate' of undefined
    at angular-daterangepicker.js:31
    at angular.js:16299
    at completeOutstandingRequest (angular.js:4924)
    at angular.js:5312(anonymous function) @ angular.js:11655
angular.js:11655 TypeError: Cannot read property 'startDate' of undefined
    at angular-daterangepicker.js:41
    at angular.js:16299
    at completeOutstandingRequest (angular.js:4924)
    at angular.js:5312(anonymous function) @ angular.js:11655
angular.js:11655 TypeError: Cannot read property 'endDate' of undefined
    at angular-daterangepicker.js:31
    at angular.js:16299
    at completeOutstandingRequest (angular.js:4924)
    at angular.js:5312(anonymous function) @ angular.js:11655
angular.js:11655 TypeError: Cannot read property 'startDate' of undefined
    at angular-daterangepicker.js:41
    at angular.js:16299
    at completeOutstandingRequest (angular.js:4924)
    at angular.js:5312
```

**Comment by krtek** [comment]
Damn. Thanks, will look into it

**Comment by krtek** [comment]
Deleted version 0.1.13 for now

**Comment by krtek** [comment]
Sorry about that. Version 0.1.14 should be OK

**Comment by mtraynham** [comment]
Np :smile: Thanks.
