### ISSUE TITLE
 TypeError: Cannot read property 'remove' of null

### ISSUE THREAD

**Issue by collaborator99** [fragaria/angular-daterangepicker#58]
This error occurs in 0.1.14 and 0.1.13:
    TypeError: Cannot read property 'remove' of null at angular-daterangepicker.js:179

That line is: 

``` javascript
return _picker.remove();
```

where _picker is null.

0.1.12 does not have this problem.

**Comment by marcelinhov2** [comment]
The problem is at method _init, line 117. This _picker needs to be set outside the el.daterangepicker method.

I will do a pull request in a few secounds.

**Comment by marcelinhov2** [comment]
Now you need to wait for the fix, or make a fork for you and point your bower.json to your repository.

**Comment by marcelinhov2** [comment]
https://github.com/fragaria/angular-daterangepicker/pull/60
