### ISSUE TITLE
"SingleDatePicker" set, but date displays as a range until you provide some input

### ISSUE THREAD

**Issue by itjustwerks** [fragaria/angular-daterangepicker#61]
I'm using the daterangepicker like this:

```
<input date-range-picker type="text" options="{singleDatePicker: true, showDropdowns: true}" ng-model="anniversaryDate" name="anniversaryDate" placeholder="Anniversary Date" class="form-control">
```

If I set the date from my controller like this: 

```
$scope.anniversaryDate = {
    startDate: moment(),
    endDate: moment()
}
```

then the <input> initially displays the date as a range with the same start/end date.

![image](https://cloud.githubusercontent.com/assets/3847303/7899196/8417645c-06e8-11e5-8527-1c7721f220c2.png)

If I click into the input, and press any key (like arrow the cursor over) the date suddenly formats correctly as a single date. Also, when a date is initially selected, it is formatted correctly without the range. It only shows up when setting the value initially. Any thoughts? The functionality is fine, but this is killing my UI.

Thanks!

**Comment by damiensauv** [comment]
+1

**Comment by babbelnedd** [comment]
This is still not working for me in `0.1.16` (release date: 16 days ago, merge date: 27 days ago). 

So, is this not in a release yet or am I doing something wrong here?

    ### template
     <input date-range-picker class="form-control date-picker" type="text"
                                    options="currentWidget.dateRange.options"
                                    ng-model="currentWidget.dateRange.fixed.from"/>

     ### controller
     // ....
     options: {
                singleDatePicker: true,
                format: 'DD.MM.YYYY'
           }
