### ISSUE TITLE
Setting initial date to null causes 'Invalid date'

### ISSUE THREAD

**Issue by petarslovic** [fragaria/angular-daterangepicker#67]
Hello, this happens on master, but not on `0.1.14`
When trying to initialize it to be empty, like so:
```
$scope.request.date = {
    startDate: null,
    endDate: null
  }
```
```
<input date-range-picker placeholder="MM/DD/YYYY" class="input-sm form-control date-picker" type="text" ng-model="request.date" />
```

It shows 'Invalid date to Invalid date'
![image](https://cloud.githubusercontent.com/assets/5387195/7960288/b792bf6a-09ff-11e5-96ec-5a3cef73dda6.png)

This has something to do with trying to make a `moment` right away with those initial null values, which then produces invalid date.

**Comment by btmdave** [comment]
I'm experiencing the same issue.  Specifically, after a date has been selected, if you attempt to clear it or reset the model, it shows the Invalid date.  Here's a screenshot after attempting to update the model with both `startDate` and `endDate` null.

![screen shot 2015-06-06 at 1 21 55 pm](https://cloud.githubusercontent.com/assets/28645/8020674/f798a12c-0c4f-11e5-8bc7-0534105e5965.png)

**Comment by seminull** [comment]
I feel that this revolves around the _setStartDate and _setEndDate methods in the directive.  I have a forked version of this library somewhere that doesn't have these problems for doing simple things like clearing the data, even without setting any arbitrary keys to null.  These aforementioned methods in the directive return using the $timeout service, which means it's likely going to come after any watchers you try to set up and creates a potential for a infinite digest loop.  I think this really needs to be rethought out with developers in mind.

**Comment by saurabh-agrawal83** [comment]
+1

**Comment by petarslovic** [comment]
I see this now works on 0.1.16. There's also a `clearable` attribute that adds Clear button instead of Cancel to the picker. Thanks! However, there's still this issue, which is related to clearing the picker - #76

**Comment by krtek** [comment]
Glad to hear that

**Comment by Wlada** [comment]
I'm using version 0.2.1 and this problem is still present. 
When I'm set initial model value to NULL, input filed is empty. 
Predefined range "Today" is selected as default and you CAN'T click on today.
If you click on some other predefined range everything will work.
When I clear the field with "clearable"  functionality, field get's default value and again selected predefined value is "Today" and you can't click on it. 

Is there some solution for setting initial value to NULL and clearing field to NULL ?

I will try to debug it and to find the problem.

**Comment by PhilBroadbent** [comment]
Wlada - any luck? I have this issue too.

**Comment by Wlada** [comment]
Hi @PhilBroadbent 

Try with this. It's not elegant solution but may work. Just add that directive to your input element

.directive('fixNullDatepicker', function($timeout) {
            return {
                restrict: 'A',
                link: function(scope, element, attr){
                    var $element  = $(element);
                    $element.data().daterangepicker.oldEndDate = null;
                    $element.data().daterangepicker.oldStartDate = null;

                    $element.on('show.daterangepicker', function (ev, picker) {
                        var l = $element.val().trim().length;

                        if (l < 1) {
                            $(document).find('.daterangepicker .ranges li').removeClass('active');

                            $element.data().daterangepicker.oldEndDate = null;
                            $element.data().daterangepicker.oldStartDate = null;
                        }
                    });
                }
            }
        })

**Comment by timvandijck** [comment]
There really should be a better way of resetting the picker when an invalid input occurs. 

For now I've created this (dirty/hacky) fix that does the job:

```
$scope.datePickerOptions = {
    eventHandlers: {
        'hide.daterangepicker' : function(ev, picker) { // Clear invalid input.
            if (ev.model.startDate === null || ev.model.startDate === null) {
                return;
            }

            if (!ev.model.startDate._isValid || !ev.model.endDate._isValid) {
                $scope.datePicker = {
                    date : {
                        startDate: new Date(),
                        endDate: new Date()
                    }
                };

                setTimeout(function() {
                    $('input.date-picker').val('');
                }, 100);
            }
        }
    }
};
```

Setting the start and end date to now (new Date) removes all "invalid date" and "null" values from the picker while the jQuery part clears your input after that.

**Comment by alexmizer** [comment]
I found that if just paste in input some min date for example->  min="'2012-01-01'" it will work fine when you try to type invalid date

**Comment by andriytkachiv** [comment]
Is there any solution for this? None of above work for me

**Comment by robbporto** [comment]
+1
