### ISSUE TITLE
Daylight Savings offset issue

### ISSUE THREAD

**Issue by idahotallpaul** [fragaria/angular-daterangepicker#69]
There appear to still be daylight saving time issues present. Using the example.html code, I run into this:

Example 1: This all works as expected.
- Select a date range of `June 1, 2015 to June 1 2015`
- The date picker displays the correct dates. 
- Output for that date object is: `{"startDate":"2015-06-01T06:00:00.000Z","endDate":"2015-06-02T05:59:59.999Z"}`. 
- Create a new date from that start date (`$scope.testDate = new Date($scope.date2.startDate);`)
- Pipe it to a date in the template `{{testDate | date}}` 
- The output is `Jun 1, 2015`

Example 2: The start date is wrong for dates outside of daylight savings time.
- Select a date range of `December 31, 2015 to December 31 2015`
- The date picker displays the correct dates. 
- Output for that date object is: `{"startDate":"2015-12-31T06:00:00.000Z","endDate":"2016-01-01T05:59:59.999Z"}`. 
- Create a new date from that start date (`$scope.testDate = new Date($scope.date2.startDate);`)
- Pipe it to a date in the template `{{testDate | date}}` 
- The output is `Dec 30, 2015`

The time offset for the dates is the same, even though one date is in DST and the other is not. There appears to be time zone compensation happening in the date picker display but not in the date picker data. My assumption would be that the displayed date would match the date data regardless of what day of the year is selected.

**Comment by BenMGilman** [comment]
+1 Having this issue on single calendar as well
