### ISSUE TITLE
Bug. Input is dirty after init, but expected pristine

### ISSUE THREAD

**Issue by arturgspb** [fragaria/angular-daterangepicker#75]
I'm sorry for not making pull request, but I spent the whole day and I could not resolve the problem.
The variable _picker somehow affect dirty state of input.
If comment code with  _picker.setStartDate(m)   _picker.setEndDate(m) datepicker of course does not work but input is pristine.

**Comment by mrthebob** [comment]
+1.  Is there a workaround for this?

**Comment by mrthebob** [comment]
If you'll open a branch from tag 0.1.17, I can submit a pull request for this.  I could submit one for HEAD as well, but that one wouldn't be tested.  (The 0.1.17 is.)
