### ISSUE TITLE
clear date range 'manually'

### ISSUE THREAD

**Issue by djindjic** [fragaria/angular-daterangepicker#76]
After manually reseting date range picker (ex):
`vm.model = {startDate: null, endDate: null};`
calendar is still showing same (old) range selected no matter that date range input box i correctly cleared. If I try to apply that same range again, my `$scope.$watch('vm.model')` cant catch it while I select different start or end date.

**Comment by saurabh-agrawal83** [comment]
+1

**Comment by m3l7** [comment]
+1

**Comment by oliroy** [comment]
+1

**Comment by dziewonski** [comment]
+1

**Comment by borodean** [comment]
Unfortunately, the bootstrap-datepicker can't clear its shown value and the maintainer isn't going to fix this:
https://github.com/dangrossman/bootstrap-daterangepicker/issues/1104

However, we may simulate the clearing by reseting the visual state to the initial one, where the current day is selected using the jQuery API. It doesn't impact the Angular world:

```js
vm.model = {startDate: null, endDate: null};

var picker = $element.find('[date-range-picker]').data('daterangepicker');
picker.setStartDate(new Date);
picker.setEndDate(new Date);
```

**Comment by michaelsogos** [comment]
Thanks @borodean to share your solution, it is acceptable while we cannot set empty dates.

**Comment by khichar-anil** [comment]
Reference [plunker](https://plnkr.co/edit/TmrfoBsj9xVDKxT0EWsD?p=preview) with @borodean suggested solution.

**Comment by ghost** [comment]
> Unfortunately, the bootstrap-datepicker can't clear its shown value and the maintainer isn't going to fix this:
> [dangrossman/daterangepicker#1104](https://github.com/dangrossman/daterangepicker/issues/1104)
> 
> However, we may simulate the clearing by reseting the visual state to the initial one, where the current day is selected using the jQuery API. It doesn't impact the Angular world:
> 
> ```js
> vm.model = {startDate: null, endDate: null};
> 
> var picker = $element.find('[date-range-picker]').data('daterangepicker');
> picker.setStartDate(new Date);
> picker.setEndDate(new Date);
> ```

Guys i used borodean solution above but after that code I called $element.click() and then everything works fines. Thank you for your help.

**Comment by kagannikita** [comment]
if you do not take into account the year, then you can disable dates through styles with dayClassName or dayStyles
