### ISSUE TITLE
Predefined Ranges

### ISSUE THREAD

**Issue by Mr-Anonymous** [fragaria/angular-daterangepicker#78]
Love this angular-daterangepicker. Thanks for creating this. I was able to get the datepicker working however I am not sure how I can set the predefined ranges in Angular like 'Yesterday, Last 7 days, Last 30 days', etc.. similar to the example in this one: http://www.daterangepicker.com/

Is it possible to do that with this module? Can you give me an example if possible please?

**Comment by Mr-Anonymous** [comment]
I was able to resolve the above question. I added the following options to controller:
```
	$scope.opts = {
		ranges: {
			'This Month': [moment().startOf('month'), moment()],
			'Today': [moment(), moment()],
			'Yesterday': [moment().subtract(1, 'day'), moment().subtract(1, 'day')],
			'Last 7 Days': [moment().subtract(6, 'days'), moment()],
			'Last 30 Days': [moment().subtract(29, 'days'), moment()],
			'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
		}
	};	
```
And added that option to the directive: 
```
<input date-range-picker options="opts" class="form-control date-picker" type="text" ng-model="daterange" /> 
```

Now, I am just wondering, how will I have the 'Last 30 Days' set as default when the page loads?

**Comment by issoft-nsiniakevich** [comment]
Just initialize ng-model value in the controller:
```
$scope.daterange = { 
   startDate: moment().subtract(29, 'days'), 
   endDate: moment() 
};
```

**Comment by amolpatel** [comment]
Thanks a lot!!!!

**Comment by Mr-Anonymous** [comment]
thank you @issoft-nsiniakevich
