### ISSUE TITLE
Cannot set minDate using min attribute

### ISSUE THREAD

**Issue by tem-akinduro** [fragaria/angular-daterangepicker#79]
Nothing happens when I set the min date using the min attribute. Am I doing something wrong?

Sample code: @a href="javascript:void(0);" daterangepicker="rangeOptions" minDate="'2012-08-10'" date-begin="startDate" date-end="endDate" class="green" ng-model="date"@
                                    @i class="fa fa-calendar icon-calendar"></i>&nbsp;&nbsp;<span>{{startDate}} - {{endDate}}</span>&nbsp;&nbsp;<i class="fa fa-angle-down icon-angle-down">@
                                @

**Comment by krtek** [comment]
You have to use `min`, not `minDate`. 
See `example.html` for example :)
