### ISSUE TITLE
It's imposible to type date range in main inputbox

### ISSUE THREAD

**Issue by akupiec** [fragaria/angular-daterangepicker#8]
Input box is refreshing to aggressively, for example if I try to change start date year from 2014 to 1999 it will end up "0001" just after pressing "1" 

I'm using default date range format and separator "YYYY-MM-DD - YYYY-MM-DD"

For my purposes it would be better to use this tree callbacks instead of default one currently implemented:

``` javascript
el.on('hide.daterangepicker', function(ev, picker) {
    refreshAll(ev, picker);
});

el.on('cancel.daterangepicker', function(ev, picker) {
    el.val(_formatted(modelCtrl.$modelValue));
});

el.on('apply.daterangepicker', function(ev, picker) {
    refreshAll(ev, picker);
});
```

**Comment by bborowin** [comment]
+1, experiencing the same issue. My workaround was to make the textbox read-only to avoid user confusion.

**Comment by zoiclabs** [comment]
+1 this is a pretty big bug. I suppose I'll go the read-only route too.

I'd prefer it if this directive would $parse the text softly, and then validate the parse using the new $validators. Providing feedback via the resulting $errors would be even better, bonus points if it's already styled nicely.

**Comment by krtek** [comment]
Well, we tried, but it's not easy fix. I suppose we will use the read-only approach by default.
