### ISSUE TITLE
After clearing, cannot "apply" already selected dates again

### ISSUE THREAD

**Issue by boskonyc** [fragaria/angular-daterangepicker#82]
If I select a date range and apply, then clear, hitting apply again on the date range produces no effect. I have to manually change the date range to some other value in order to have the apply take effect.

**Comment by kijanawoodard** [comment]
+1

**Comment by boskonyc** [comment]
The issue should be closed--- I think I was using the directive inappropriately .The real way to act on changes to date are not to link an event watcher to the model, but rather to setup a listener on the "apply" event as an attribute to the directive declaration.

**Comment by kijanawoodard** [comment]
The problem we're seeing is that if the user clears the date manually, the control still thinks the previous date is still selected and won't let you select it again.

In the simple case, if the model is set to null, you can't pick "today" because it's already selected in the control.

**Comment by boskonyc** [comment]
But the apply event still fires when the apply button is click, right? Can't you use an event trigger to perform whatever functionality is required on the date selection on the apply event?

**Comment by mschaeuble** [comment]
Catching the event doesn't work neither because the arguments are not passed properly. See also my comment in https://github.com/fragaria/angular-daterangepicker/issues/119
