### ISSUE TITLE
Add npm package

### ISSUE THREAD

**Issue by thethomaseffect** [fragaria/angular-daterangepicker#84]
Our project is trying to remove bower as a dependency and only use npm for our client-side dependencies. Could you publish this package on npm as well as bower please? :)

**Comment by krtek** [comment]
Hello, 
please send PR for this. I'm not sure how to do that.

**Comment by thethomaseffect** [comment]
Sure, I can create the package.json file but you'd need to update it with your own details seeing as I'm not a repo maintainer. If you clone the repo, run `npm init` and follow the prompts and then follow the instructions [here](https://docs.npmjs.com/getting-started/publishing-npm-packages) it takes about 5 mins in total.

**Comment by borodean** [comment]
@krtek it looks like the package hasn't been published yet, so the whole thing doesn't work. Could you do `npm publish`?

**Comment by malykhinvi** [comment]
Any update on this? Seems like the package has not published yet.

**Comment by ashsearle** [comment]
After accidentally publishing 0.2.2 to npm in January, I've now made some changes to package.json and published a 0.2.3-alpha1 release which (I hope) is more usable via npm.

@krtek please sign up on npm and I'll hand ownership of the npm package to you

**Comment by Michaelzvu** [comment]
Could you publish the latest version? (0.3.0)
