### ISSUE TITLE
Struggling to get the selected date in controller after apply.daterangepicker event

### ISSUE THREAD

**Issue by corientdev** [fragaria/angular-daterangepicker#87]
Struggling to get the selected start date and end date in controller after apply.daterangepicker event

**Comment by vaesbart** [comment]
I may be having a similar problem: I have to click "apply" twice before the model actually gets updated.

**Comment by Vimos** [comment]
Hope someone can offer a hint on how to fix this, "Click twice that model gets updated".

**Comment by Vimos** [comment]
Hi, it may be my fault. It finally works if I change the code to this:

```
    $scope.options = {
        eventHandlers: {
            'apply.daterangepicker': function (ev, picker) {
                var start = picker.startDate.format('YYYY-MM-DD');
                var end = picker.endDate.format('YYYY-MM-DD');
                $scope.drawChartTable(start, end);
            }
        }
    };
```

New date should be read from picker.

**Comment by umdstu** [comment]
On a related note, I get undefined for the 'picker' parameter with i click apply. 'ev' is there but i need 'picker' obviously for the values, what could I be doing?

angular-datepicker.js version: master
datepicker.js version: 2.1.13

**Comment by ranieri82** [comment]
Any word on this...just opened an issue on picker being undefined

**Comment by umdstu** [comment]
I haven't made any discovories yet. Something in the angular code I suspect. I double checked the daterangerpicker.js listener and it sees the picker object.

**Comment by umdstu** [comment]
@Vimos can you provide your actual implementation of the picker? As in, is it using an <input> or different tag, ie. <div>? Are you passing the eventHandler options via the options param or through options configuration in the controller?
Thanks!

**Comment by mschaeuble** [comment]
I think this issue can be closed in favor of https://github.com/fragaria/angular-daterangepicker/issues/119
See also my latest comment in there.
