### ISSUE TITLE
missing some timepicker options

### ISSUE THREAD

**Issue by aurel-tackoen** [fragaria/angular-daterangepicker#88]
"timePicker24Hour": true
    "timePickerIncrement": 60

this two options doesn't seems to be working.

am I missing something ?

**Comment by disname** [comment]
Have the same problem.Version 0.1.16

**Comment by disname** [comment]
Solved.You need to use 
```javascript
timePicker12Hour:false 
```
instead of timePicker24Hour

**Comment by krtek** [comment]
Thanks for figuring this out

**Comment by aurel-tackoen** [comment]
yes thank you :)
i'll try this tmrw
