### ISSUE TITLE
Can not add  event handler

### ISSUE THREAD

**Issue by ettigr** [fragaria/angular-daterangepicker#93]
According to the documentation , event handlers can be passed in through the eventHandlers
 
<input date-range-picker class="form-control date-picker" type="text" ng-model="date"
options="{eventHandlers: {'cancel.daterangepicker': function(ev, picker) { ... }}}"/>

I tried to put instead of ... any JavaScript code like : date='';  - got parse error

**Comment by ettigr** [comment]
Did it like this:
in html
  <input date-range-picker options="dateRangePickerOptions"... name="date" ng-model="date"/>  -->
in js
            $scope.dateRangePickerOptions = {
                eventHandlers: {
                    'cancel.daterangepicker': function() { 
                        date = "";
                    }
                },
                singleDatePicker: true, 
                timePicker: true , 
                clearable: true , 
                locale: {format: 'MM/DD/YYYY h:mm A'}
             };

**Comment by ettigr** [comment]
html :

 <input date-range-picker options="dateRangePickerOptions"  ng-model="date"   ... />

**Comment by chillyistkult** [comment]
Can confirm it's completly broken atm.

**Comment by anurag619** [comment]
I got the 'apply' event handler working:

`
js:
a.dateRangePickerOptions = {locale: {format: 'DD MMM'}, 
		separator: 'to',
		eventHandlers: {'apply.daterangepicker': function(ev, picker) { 
		a.setDateTime(ev.model);
		 }}
 };
html:
<input date-range-picker class="form-control date-picker" type="text" ng-model="datePicker" options="dateRangePickerOptions" />
`
