### ISSUE TITLE
Starting date on load is NaN. 

### ISSUE THREAD

**Issue by djaevlen** [fragaria/angular-daterangepicker#94]
Hi there,

When i use your example (https://github.com/fragaria/angular-daterangepicker/blob/master/example.html) and provide it with the dependencies in a plunker, the input fields are empty and my $scope.date's is "NaN". Not matter if i try to use hardcoded dates or moment.js dates.  

My plunkr: http://plnkr.co/edit/ENvgRQinaixbpwI4ab1l?p=preview

Can you please take a look on this?

**Comment by alexpx** [comment]
+1

**Comment by cpeker** [comment]
Hi,
Is there any solution for this?
I can not call the directive with default values.

Thanks

**Comment by alexpx** [comment]
It's happening when working with 2.X version of bootstrap daterangepicker.

**Comment by krtek** [comment]
@alexpx Thanks! Didn't thought of this – 1.x version works. 
Must see what happens, will just update dependency now.

**Comment by alexpx** [comment]
Thanks. 
it's important that the directive will work with 2.x version since it introduced some cool stuff.

**Comment by djaevlen** [comment]
Ahh yeah thanks. Changing to 1.x did the trick. Gonna use 1.x from now on until 2.x gets support.

**Comment by Abhith** [comment]
+1
