### ISSUE TITLE
Unable to set startDate and endDate when date-range-picker in popover

### ISSUE THREAD

**Issue by ramprakash-ravi** [fragaria/angular-daterangepicker#95]
I'm using the date-range-picker on my angular popover :
https://github.com/angular-ui/bootstrap/tree/master/src/popover

but i'm unable to get the value updated when i choose any start or end date and click Apply button.
startDate and endDate are always null when date-range-picker used within popover.

**Comment by vorenus181** [comment]
try use ng-init
