### ISSUE TITLE
Compatibility with version 2.x

### ISSUE THREAD

**Issue by Mr-Anonymous** [fragaria/angular-daterangepicker#99]
I see from the description page that the `angular-daterangepicker` is not yet compatible with Bootstrap Datepicker v 2.x yet. Do you have plans to release an updated version compatible with 2.x anytime soon?

**Comment by alexpx** [comment]
+1

**Comment by jrencz** [comment]
:+1:

**Comment by YidingW** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
